/**
 * Episode 06 — The Kirata
 * Vana Parva · Arjuna’s penance · Shiva as the hunter · Pashupatastra
 */
export const EPISODE = {
  id: "06",
  slug: "kirata",
  title: "The Kirata",
  subtitle: "Arjuna and the Lord of the mountains",
  style: "cinematic-plates",
  stillsDir: "episodes/06-kirata/stills/",
  voice: {
    provider: "grok-tts",
    voice_id: "orion",
    cache: "ep06-v1",
    note: "Grok TTS orion — deep heroic narration",
    base: "episodes/06-kirata/audio/",
  },
  totalSec: 102,
  stills: {
    poster: "episodes/06-kirata/stills/poster.jpg",
  },
  plates: {
    wide: "plate-wide.jpg",
    penance: "plate-penance.jpg",
    boar: "plate-boar.jpg",
    hunter: "plate-hunter.jpg",
    duel: "plate-duel.jpg",
    equal: "plate-equal.jpg",
    reveal: "plate-reveal.jpg",
    gift: "plate-gift.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  end: {
    title: "End of Episode 06",
    line: "The weapon is given to the hand that has already bowed.",
    next: "play.html?ep=07",
    nextLabel: "Play Episode 07",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      audio: "orion-00.mp3",
      who: "Narrator",
      text: "To win the weapons of heaven, Arjuna climbs alone into the high Himalaya.",
    },
    {
      t: 10,
      plate: "penance",
      zoom: 1.14,
      panX: 0.02,
      panY: -0.03,
      audio: "orion-01.mp3",
      who: "Narrator",
      text: "There he stands in fierce penance — still as stone, mind fixed on Mahadeva.",
    },
    {
      t: 22,
      plate: "boar",
      zoom: 1.12,
      panX: -0.03,
      panY: 0,
      audio: "orion-02.mp3",
      who: "Narrator",
      text: "A terrible boar charges through the pines. Two arrows leave two bows at once.",
    },
    {
      t: 34,
      plate: "hunter",
      zoom: 1.12,
      panX: 0.04,
      panY: -0.02,
      audio: "orion-03.mp3",
      who: "Narrator",
      text: "A mountain hunter claims the kill. Arjuna will not yield the honor of the shot.",
    },
    {
      t: 44,
      plate: "duel",
      zoom: 1.18,
      panX: 0.02,
      panY: -0.04,
      audio: "orion-04.mp3",
      who: "Narrator",
      text: "Bow meets bow. The kirata matches Arjuna blow for blow — and the forest shakes.",
    },
    {
      t: 56,
      plate: "equal",
      zoom: 1.16,
      panX: 0,
      panY: -0.02,
      audio: "orion-05.mp3",
      who: "Narrator",
      text: "Arjuna’s strength fails against an equal. He falls, astonished, at a hunter’s feet.",
    },
    {
      t: 68,
      plate: "reveal",
      zoom: 1.2,
      panX: 0.03,
      panY: -0.05,
      audio: "orion-06.mp3",
      who: "Narrator",
      text: "Then the kirata shines with a thousand suns. It is Shiva, the Lord, smiling.",
    },
    {
      t: 80,
      plate: "gift",
      zoom: 1.14,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-07.mp3",
      who: "Narrator",
      text: "Pleased by courage and devotion, Mahadeva grants the Pashupatastra.",
    },
    {
      t: 90,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      audio: "orion-08.mp3",
      who: "Narrator",
      text: "So the archer who saw only the eye is given the weapon that ends the war of ages.",
    },
    {
      t: 100,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
