/**
 * Episode registry — add entries as the series grows.
 * Each playable ep has a module under episodes/<id>/script.js
 */
export const EPISODES = [
  {
    id: "01",
    slug: "birds-eye",
    title: "The Bird's Eye",
    sanskrit: "पक्षिणश्चक्षुः",
    chapter: "Ādi Parva · training of the princes",
    duration: "~90s",
    status: "live",
    blurb:
      "Drona tests his pupils. Only Arjuna sees what must be seen — the eye, and nothing else.",
    play: "play.html?ep=01",
  },
  {
    id: "02",
    slug: "swayamvara",
    title: "The Fish's Eye",
    sanskrit: "मत्स्यचक्षुः",
    chapter: "Ādi Parva · Draupadi’s swayamvara",
    duration: "~96s",
    status: "live",
    blurb:
      "At Drupada’s court the prize is won by looking only at the reflection — Arjuna strings the bow and strikes the fish’s eye.",
    play: "play.html?ep=02",
  },
  {
    id: "03",
    slug: "bhima-bakasura",
    title: "Bhima and Bakasura",
    sanskrit: "भीमबकासुरः",
    chapter: "Ādi Parva · Ekachakra",
    duration: "~100s",
    status: "live",
    blurb:
      "In Ekachakra a rakshasa takes a daily due. Kunti sends Bhima — and the strong keep the helpless safe.",
    play: "play.html?ep=03",
  },
  {
    id: "04",
    slug: "akshayapatra",
    title: "The Akshayapatra",
    sanskrit: "अक्षयपात्रम्",
    chapter: "Vana Parva · Durvasa’s visit",
    duration: "~130s",
    status: "live",
    blurb:
      "When the vessel is empty and Durvasa arrives hungry, one grain of grace is enough — Krishna answers Draupadi’s prayer.",
    play: "play.html?ep=04",
  },
  {
    id: "05",
    slug: "yaksha-prashna",
    title: "Yaksha Prashna",
    sanskrit: "यक्षप्रश्नः",
    chapter: "Vana Parva · the lake of questions",
    duration: "~102s",
    status: "live",
    blurb:
      "Thirst leads to a silent lake. Brothers fall; Yudhishthira answers the yaksha — and dharma restores them.",
    play: "play.html?ep=05",
  },
  {
    id: "06",
    slug: "kirata",
    title: "The Kirata",
    sanskrit: "किरातार्जुनम्",
    chapter: "Vana Parva · Arjuna’s penance",
    duration: "~102s",
    status: "live",
    blurb:
      "In the Himalaya Arjuna meets a mountain hunter — and wins the Pashupatastra from Shiva himself.",
    play: "play.html?ep=06",
  },
  {
    id: "07",
    slug: "jayadratha",
    title: "Jayadratha",
    sanskrit: "जयद्रथः",
    chapter: "Vana Parva · the forest abduction",
    duration: "~100s",
    status: "live",
    blurb:
      "While the brothers hunt, Jayadratha seizes Draupadi — and the Pandavas turn the chase into justice.",
    play: "play.html?ep=07",
  },
  {
    id: "08",
    slug: "peace-embassy",
    title: "The Peace Embassy",
    sanskrit: "शान्तिदूतः",
    chapter: "Udyoga Parva · Krishna at Hastinapura",
    duration: "~102s",
    status: "live",
    blurb:
      "Krishna asks for five villages. Duryodhana refuses. Peace fails — and Kurukshetra draws near.",
    play: "play.html?ep=08",
  },
  {
    id: "09",
    slug: "gita",
    title: "The Bhagavad Gita",
    sanskrit: "भगवद्गीता",
    chapter: "Bhishma Parva · Kurukshetra opens",
    duration: "~104s",
    status: "live",
    blurb:
      "On Kurukshetra Arjuna’s bow falls — until Krishna’s song of dharma lights the field, and the war of ages begins.",
    play: "play.html?ep=09",
  },
  {
    id: "10",
    slug: "bhishma-fall",
    title: "The Fall of Bhishma",
    sanskrit: "भीष्मपतनम्",
    chapter: "Bhishma Parva · tenth day",
    duration: "~104s",
    status: "live",
    blurb:
      "On the tenth day the grandsire will not strike Shikhandi — Arjuna’s arrows find him, and Bhishma takes the bed of shafts until the sun turns north.",
    play: "play.html?ep=10",
  },
  {
    id: "11",
    slug: "chakravyuha",
    title: "The Chakravyuha",
    sanskrit: "चक्रव्यूहः",
    chapter: "Drona Parva · thirteenth day",
    duration: "~104s",
    status: "live",
    blurb:
      "Drona arrays a wheel of war. Abhimanyu knows the way in — not the way out — and the thirteenth day darkens.",
    play: "play.html?ep=11",
  },
  {
    id: "12",
    slug: "jayadratha-vadha",
    title: "Jayadratha Falls",
    sanskrit: "जयद्रथवधः",
    chapter: "Drona Parva · fourteenth day",
    duration: "~104s",
    status: "live",
    blurb:
      "Arjuna vows Jayadratha dies before sunset. Krishna veils the sun — and the fourteenth day keeps its word.",
    play: "play.html?ep=12",
  },
  {
    id: "13",
    slug: "ghatotkacha",
    title: "Ghatotkacha",
    sanskrit: "घटोत्कचः",
    chapter: "Drona Parva · night of the fourteenth",
    duration: "~104s",
    status: "live",
    blurb:
      "Night after Jayadratha. Ghatotkacha darkens the field — and Karna spends the dart that was kept for Arjuna.",
    play: "play.html?ep=13",
  },
  {
    id: "14",
    slug: "drona-fall",
    title: "The Fall of Drona",
    sanskrit: "द्रोणवधः",
    chapter: "Drona Parva · fifteenth day",
    duration: "~136s",
    status: "live",
    blurb:
      "Drona cannot be beaten in arms. An elephant dies, a truthful king speaks half a truth — and the guru lays down his bow.",
    play: "play.html?ep=14",
  },
  {
    id: "15",
    slug: "narayanastra",
    title: "The Narayana Weapon",
    sanskrit: "नारायणास्त्रम्",
    chapter: "Drona Parva · fifteenth day, afternoon",
    duration: "~112s",
    status: "live",
    blurb:
      "Ashwatthama looses the Narayana weapon. Krishna’s counsel: lay down your arms — and the fire spares whoever stands unarmed.",
    play: "play.html?ep=15",
  },
  {
    id: "16",
    slug: "karna-commander",
    title: "Karna Takes Command",
    sanskrit: "कर्णाभिषेकः",
    chapter: "Karna Parva · sixteenth and seventeenth days",
    duration: "~112s",
    status: "live",
    blurb:
      "Drona has fallen. Karna leads the Kaurava host — and asks for one charioteer to match Krishna: proud Shalya, who takes the reins with scorn.",
    play: "play.html?ep=16",
  },
  {
    id: "17",
    slug: "karna-fall",
    title: "The Fall of Karna",
    sanskrit: "कर्णवधः",
    chapter: "Karna Parva · seventeenth day",
    duration: "~112s",
    status: "live",
    blurb:
      "Karna and Arjuna meet at last. A serpent arrow takes only a crown, the earth seizes Karna’s wheel — and the son of the Sun falls in the afternoon light.",
    play: "play.html?ep=17",
  },
  {
    id: "18",
    slug: "shalya-fall",
    title: "The Fall of Shalya",
    sanskrit: "शल्यवधः",
    chapter: "Shalya Parva · eighteenth day",
    duration: "~112s",
    status: "live",
    blurb:
      "Karna is gone, and old Shalya leads what is left. Gentle Yudhishthira rides out in anger, a worshipped dart in his hand — and Duryodhana walks alone to a lake.",
    play: "play.html?ep=18",
  },
  {
    id: "19",
    slug: "mace-duel",
    title: "The Mace Duel",
    sanskrit: "गदायुद्धम्",
    chapter: "Shalya Parva · eighteenth day",
    duration: "~112s",
    status: "live",
    blurb:
      "Duryodhana rises from the lake to face Bhima, mace to mace. Arjuna gives a silent sign, an old vow is kept — and Balarama raises his plough in fury.",
    play: "play.html?ep=19",
  },
];
