/**
 * Episode 10 — The Fall of Bhishma
 * Bhishma Parva · tenth day; Shikhandi; the bed of arrows
 */
export const EPISODE = {
  id: "10",
  slug: "bhishma-fall",
  title: "The Fall of Bhishma",
  subtitle: "Tenth day of Kurukshetra",
  style: "cinematic-plates",
  stillsDir: "episodes/10-bhishma-fall/stills/",
  voice: {
    provider: "grok-tts",
    voice_id: "orion",
    cache: "ep10-v1",
    note: "Grok TTS orion — deep heroic narration",
    base: "episodes/10-bhishma-fall/audio/",
  },
  totalSec: 104,
  stills: {
    poster: "episodes/10-bhishma-fall/stills/poster.jpg",
  },
  plates: {
    wide: "plate-wide.jpg",
    storm: "plate-storm.jpg",
    counsel: "plate-counsel.jpg",
    shikhandi: "plate-shikhandi.jpg",
    vow: "plate-vow.jpg",
    arrows: "plate-arrows.jpg",
    fall: "plate-fall.jpg",
    bed: "plate-bed.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  end: {
    title: "End of Episode 10",
    line: "The pitamaha waits upon his bed of arrows for the sun to turn north.",
    next: "play.html?ep=11",
    nextLabel: "Episode 11 — The Chakravyuha",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    silver: "#c5d0dc",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      audio: "orion-00.mp3",
      who: "Narrator",
      text: "On the tenth day the grandsire still holds the field — a white flame among the banners.",
    },
    {
      t: 12,
      plate: "storm",
      zoom: 1.12,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-01.mp3",
      who: "Narrator",
      text: "His arrows fly like a river of light. The Pandava host cannot pass the grandsire.",
    },
    {
      t: 24,
      plate: "counsel",
      zoom: 1.14,
      panX: -0.02,
      panY: -0.02,
      audio: "orion-02.mp3",
      who: "Narrator",
      text: "Krishna speaks to Arjuna: place Shikhandi before you — the vow will open the way.",
    },
    {
      t: 36,
      plate: "shikhandi",
      zoom: 1.14,
      panX: 0.03,
      panY: -0.02,
      audio: "orion-03.mp3",
      who: "Narrator",
      text: "Shikhandi of Panchala walks to the front — a warrior the grandsire will not strike.",
    },
    {
      t: 48,
      plate: "vow",
      zoom: 1.16,
      panX: 0,
      panY: -0.03,
      audio: "orion-04.mp3",
      who: "Narrator",
      text: "Bhishma lowers his weapons. He will not raise a shaft against one born as Amba.",
    },
    {
      t: 60,
      plate: "arrows",
      zoom: 1.14,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-05.mp3",
      who: "Narrator",
      text: "From behind that shield Arjuna looses Gandiva — and the grandsire does not answer.",
    },
    {
      t: 72,
      plate: "fall",
      zoom: 1.18,
      panX: 0,
      panY: 0.02,
      audio: "orion-06.mp3",
      who: "Narrator",
      text: "He falls as a great tree falls — slowly, and the earth receives a pitamaha.",
    },
    {
      t: 84,
      plate: "bed",
      zoom: 1.12,
      panX: -0.02,
      panY: -0.02,
      audio: "orion-07.mp3",
      who: "Narrator",
      text: "Upon a bed of arrows he lies and watches the sun — waiting for the northern turn.",
    },
    {
      t: 95,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      audio: "orion-08.mp3",
      who: "Narrator",
      text: "Thus the tenth day ended. The grandsire would not rise until the sun turned north.",
    },
    {
      t: 102,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
