/**
 * Episode 02 — The Fish's Eye (Draupadi’s Swayamvara)
 * Same pipeline as Ep 01: cinematic plates + Grok TTS (orion) + flute/tabla.
 */
export const EPISODE = {
  id: "02",
  slug: "swayamvara",
  title: "The Fish's Eye",
  subtitle: "Draupadi’s swayamvara",
  style: "cinematic-plates",
  stillsDir: "episodes/02-swayamvara/stills/",
  voice: {
    provider: "grok-tts",
    voice_id: "orion",
    cache: "ep02-v6-curtain-largetank",
    note: "Grok TTS orion — v4 ceiling-high aquarium + split aim geometry",
    base: "episodes/02-swayamvara/audio/",
  },
  totalSec: 96,
  stills: {
    poster: "episodes/02-swayamvara/stills/poster.jpg",
  },
  plates: {
    wide: "plate-wide.jpg",
    challenge: "plate-challenge.jpg",
    kings: "plate-kings.jpg",
    draupadi: "plate-draupadi.jpg",
    brahmin: "plate-brahmin.jpg",
    aim: "plate-aim.jpg",
    hit: "plate-hit.jpg",
    garland: "plate-garland.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  end: {
    title: "End of Episode 02",
    line: "The hand that saw truly won the prize.",
    next: "index.html",
    nextLabel: "All episodes",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      audio: "orion-00.mp3",
      who: "Narrator",
      text: "In the court of King Drupada, suitors gather for Draupadi’s swayamvara.",
    },
    {
      t: 9,
      plate: "challenge",
      zoom: 1.12,
      panX: 0.04,
      panY: -0.03,
      audio: "orion-01.mp3",
      who: "Narrator",
      text: "The test is set: high under the palace roof, a glass aquarium hangs like a chandelier. Hit its eye — but look only down into the pool’s reflection.",
    },
    {
      t: 20,
      plate: "kings",
      zoom: 1.1,
      panX: -0.03,
      panY: 0,
      audio: "orion-02.mp3",
      who: "Narrator",
      text: "Prince after prince fails. The great bow will not yield to pride alone.",
    },
    {
      t: 30,
      plate: "draupadi",
      zoom: 1.14,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-03.mp3",
      who: "Narrator",
      text: "Draupadi waits with the garland, calm as the challenge grows heavier.",
    },
    {
      t: 40,
      plate: "brahmin",
      zoom: 1.12,
      panX: 0.05,
      panY: 0,
      audio: "orion-04.mp3",
      who: "Narrator",
      text: "Then a young brahmin steps forward — quiet, steady. None yet know him as Arjuna.",
    },
    {
      t: 50,
      plate: "aim",
      zoom: 1.22,
      panX: 0.06,
      panY: -0.04,
      audio: "orion-05.mp3",
      who: "Narrator",
      text: "He strings the bow, looks only down into the water, and aims the arrow up — finding the eye.",
    },
    {
      t: 60,
      plate: "hit",
      zoom: 1.28,
      panX: 0.04,
      panY: -0.06,
      audio: "orion-06.mp3",
      who: "Narrator",
      text: "The arrow flies. The fish is struck. The court falls silent — then roars.",
    },
    {
      t: 70,
      plate: "garland",
      zoom: 1.16,
      panX: 0,
      panY: 0,
      audio: "orion-07.mp3",
      who: "Narrator",
      text: "Draupadi places the garland on his neck. The prize is won by skill, not boast.",
    },
    {
      t: 82,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      audio: "orion-08.mp3",
      who: "Narrator",
      text: "Once more Arjuna proves the lesson of the garden: see only what must be hit.",
    },
    {
      t: 94,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
