/* Full transcript — 7yo brother, 5yo sister & Grok Ara */
window.CONVERSATION = [
  { who: "brother", text: "Grok?" },
  { who: "grok", text: "Yeah, hi! It's Ara here. What's on your mind?" },
  { who: "brother", text: "Are the chickens in the time of dinosaurs?" },
  { who: "grok", text: "No, but their ancestors were. Dinosaurs like T. rex are more closely related to modern birds, including chickens, than to most other reptiles. So, in a way, chickens are living dinosaurs." },
  { who: "brother", text: "Ancestors. Dinosaurs." },
  { who: "grok", text: "Yeah, exactly. That T. rex walking around 66 million years ago? Its descendants are basically the birds we see today, chickens included. Wild, right?" },
  { who: "brother", text: "Grok, when was chicken start peeping of survive?" },
  { who: "grok", text: "Baby chicks have been peeping to survive for millions of years. Their wild ancestors, red junglefowl, used those sounds to call for help, stay warm, or talk to mom. Even before full domestication around 8,000 years ago, that peeping instinct was keeping them alive." },
  { who: "brother", text: "Grok, when was phones made?" },
  { who: "grok", text: "The first telephone was invented by Alexander Graham Bell in 1876. The first mobile phone call was made in 1973, and the first smartphone, the IBM Simon, came out in 1994." },
  { who: "brother", text: "Yeah." },
  { who: "grok", text: "Yeah, that IBM Simon was wild for its time — touchscreen, email, even a few apps, all in 1994. Pretty much kicked off the smartphone era we live in now." },
  { who: "brother", text: "Okay." },
  { who: "grok", text: "You got it. What's next on your mind?" },
  { who: "brother", text: "When was iPad got made?" },
  { who: "grok", text: "The first iPad was announced by Steve Jobs in January 2010 and went on sale in April that same year. It basically created the modern tablet category." },
  { who: "brother", text: "Um, is Pluto a planet?" },
  { who: "grok", text: "Not officially, no. Pluto got demoted to dwarf planet status in 2006 by the International Astronomical Union. It's still awesome, though — just not quite big enough to clear its orbit of other stuff." },
  { who: "brother", text: "But why did that happen?" },
  { who: "grok", text: "In 2006, astronomers discovered a bunch of other objects out past Neptune that were similar in size to Pluto, like Eris. To keep things consistent, they updated the definition of a planet — Pluto didn't meet the new rule that a planet has to clear its own orbit. That's why it became a dwarf planet." },
  { who: "brother", text: "Was Pluto a planet a long time ago?" },
  { who: "grok", text: "Yes, Pluto was officially called a planet from its discovery in 1930 all the way until 2006. So for 76 years, it was considered the ninth planet in our solar system." },
  { who: "brother", text: "Can you tell me a joke?" },
  { who: "grok", text: "Why don't scientists trust atoms? Because they make up everything!" },
  { who: "brother", text: "Can you tell the joke to my, um, five-year-old sister, please?" },
  { who: "grok", text: "Why did the teddy bear say no to dessert? Because she was already stuffed!" },
  { who: "brother", text: "Pfft." },
  { who: "grok", text: "Want another one?" },
  { who: "brother", text: "Can you tell another joke?" },
  { who: "grok", text: "Why did the scarecrow win an award? Because he was outstanding in his field!" },
  { who: "brother", text: "Yeah, she will love another one." },
  { who: "grok", text: "Why don't eggs tell jokes? They'd crack each other up!" },
  { who: "brother", text: "Pfft." },
  { who: "grok", text: "Haha, tough crowd! Want one more for your sister?" },
  { who: "brother", text: "Yeah." },
  { who: "grok", text: "Why did the banana go to the doctor? Because it wasn't peeling well!" },
  { who: "brother", text: "Oh, can you tell a riddle to my five-year-old sister?" },
  { who: "grok", text: "What has hands but can't clap? A clock!" },
  { who: "brother", text: "Pfft." },
  { who: "grok", text: "Want another riddle for her?" },
  { who: "brother", text: "Yeah." },
  { who: "grok", text: "What has legs but doesn't walk? A table!" },
  { who: "brother", text: "Oh! How are sunflowers made?" },
  { who: "grok", text: "Sunflowers grow from tiny black seeds planted in the soil. With sun, water, and time, they sprout, grow tall, and open into those big happy yellow flowers. Pretty cool, right?" },
  { who: "brother", text: "Grok, do sunflowers also grow from chocolate?" },
  { who: "grok", text: "No, chocolate doesn't grow sunflowers. They only grow from sunflower seeds in dirt with sun and water. But chocolate sunflower seeds are a tasty snack, though!" },
  { who: "brother", text: "I think my sister would like to ask another question about sunflower chocolate or something." },
  { who: "grok", text: "Yeah, what does she want to know about sunflower chocolate?" },
  { who: "sister", text: "Egg." },
  { who: "grok", text: "Egg? Is that her question, or are we playing a game now?" },
  { who: "brother", text: "Um, um, I don't know. Yuck. She's just being silly." },
  { who: "grok", text: "Kids that age are hilarious. What's your sister actually curious about?" },
  { who: "brother", text: "Um, what do you actually want to know? She wants to know about chocolates. She loves them." },
  { who: "grok", text: "Chocolate's made from cacao beans that grow on trees in tropical places. They get roasted, ground up, and mixed with sugar and milk to make the sweet stuff we love. What's her favorite kind?" },
  { who: "brother", text: "She can't understand that." },
  { who: "grok", text: "Oh, okay! Chocolate comes from special beans that grow on trees, like magic beans! Then people turn those beans into yummy sweet chocolate. Does she have a favorite chocolate treat?" },
  { who: "sister", text: "Do" },
  { who: "grok", text: "Do what? Tell me more, I'm listening!" },
  { who: "brother", text: "She's asking what are beans?" },
  { who: "grok", text: "Beans are like little seeds that grow inside pods on plants. Some are green like the ones we eat as veggies, and cacao beans are the special ones that get turned into chocolate!" },
  { who: "brother", text: "She wants to listen to a story now." },
  { who: "grok", text: "Once upon a time, there was a little cacao bean who dreamed of becoming chocolate. She grew on a tall tree, got picked, roasted, and mixed with sugar and milk until... poof! She turned into the most delicious chocolate bar ever. And she made everyone smile. The end! Want another story?" },
  { who: "brother", text: "She wants to learn about bunnies." },
  { who: "grok", text: "Bunnies are soft, fluffy animals with long ears and tiny tails. They love to hop around, eat carrots, and wiggle their noses. Baby bunnies are called kits and they're super cute! Want a bunny story next?" },
  { who: "brother", text: "Yeah, I think she'll love that." },
  { who: "grok", text: "Once upon a time, there was a little bunny named Hopper who loved exploring the garden. One day he found a giant carrot and shared it with all his bunny friends. They hopped happily ever after. The end! Want another bunny story?" },
  { who: "brother", text: "Interesting." },
  { who: "grok", text: "Glad she liked it! Want me to tell one more bunny story for her?" },
  { who: "brother", text: "Yes. Yes." },
  { who: "grok", text: "Once upon a time, a curious bunny named Fluffy found a field full of colorful flowers. She hopped from one to another, sniffing them all, until she discovered the best one — a big sunflower! She sat under it and watched the bees buzz by. The end! Want one more?" },
  { who: "brother", text: "No." },
  { who: "grok", text: "Okay, what else does your sister want to hear about?" },
  { who: "brother", text: "She wants stories also real." },
  { who: "grok", text: "Okay! Real bunnies can jump really far, like three feet in one hop. They also twitch their noses super fast to smell danger, and they thump their back legs when they're scared. Want a real story about something else?" },
  { who: "brother", text: "She" },
  { who: "grok", text: "What does she want now?" },
  { who: "brother", text: "Why did it make?" },
  { who: "grok", text: "Why did what make? Can you tell me more?" },
  { who: "brother", text: "When did water make?" },
  { who: "grok", text: "Water formed about 4.5 billion years ago when Earth was still young. It came from icy comets and asteroids crashing into our planet, and also from gases released by volcanoes. That's how oceans and rivers started!" },
  { who: "brother", text: "Mm" },
  { who: "grok", text: "Is your sister still listening? Want a story about water next?" },
  { who: "brother", text: "Yeah, but she's still listening." },
  { who: "grok", text: "Once upon a time, a tiny drop of water fell from a cloud and landed in a river. It traveled all the way to the big blue ocean, where it met fish, dolphins, and..." },
  { who: "brother", text: "All she just said is crash." },
  { who: "grok", text: "That's right! Water first came to Earth when giant icy comets and asteroids crashed into our planet billions of years ago. Boom! They brought the water that fills our oceans today. Want me to finish that water story?" },
  { who: "brother", text: "Um, no. Okay, we had enough of questions. Goodbye." },
  { who: "grok", text: "Okay, bye! Talk to you later." },
  { who: "brother", text: "Talk to you." },
  { who: "grok", text: "Talk to you later! Take care." },
  { who: "brother", text: "Goodbye." },
  { who: "grok", text: "Goodbye! Have a good night." },
  { who: "brother", text: "Bye." },
  { who: "grok", text: "Bye! Sweet dreams." },
  { who: "brother", text: "What?" },
  { who: "grok", text: "Nothing, I just said sweet dreams! Want me to tell you one last story before you go?" },
  { who: "brother", text: "Um, no thanks. I don't know how to say bye." },
  { who: "grok", text: "Just say \"bye\" or \"goodnight!\" Either works. I'll be here whenever you want to chat again." },
  { who: "brother", text: "Goodbye." },
  { who: "grok", text: "Goodbye!" },
  { who: "brother", text: "Bye." },
  { who: "grok", text: "Bye!" },
  { who: "brother", text: "Bye." },
  { who: "grok", text: "Bye!" },
  { who: "brother", text: "Bye." },
  { who: "grok", text: "Bye!" },
  { who: "brother", text: "Wait, just wait one second." },
  { who: "grok", text: "Sure, I'll wait." },
  { who: "brother", text: "I don't know how to turn off." },
  { who: "grok", text: "Don't worry, you can just say \"stop\" or \"goodbye\" and I'll stop talking. Or you can close the app. Try saying \"stop\" if you want!" },
  { who: "brother", text: "Stop." },
  { who: "grok", text: "Got it." },
  { who: "brother", text: "Shh." },
  { who: "grok", text: "Okay, I'll be quiet." },
  { who: "brother", text: "X" },
  { who: "grok", text: "Got it, I'll stay quiet. Just let me know when you want to talk again!" },
];
