/**
 * Episode 05 — Yaksha Prashna
 * Vana Parva · Yakṣa-praśna (lake ordeal) · Dharma tests Yudhiṣṭhira
 *
 * Audio: orion-00…08 re-rendered 2026-10-03 with free local Kokoro-82M bm_george
 * (tools/render_local_voice.sh, speed 0.9); PRONOUNCE for Yudhishthira/Pandavas/yaksha/Nakula/Dharma.
 * Beat t retimed from ffprobe (12 s grid; clip ends ≥1 s before next beat).
 * Music: named Hindustani raga Bhairav (never default flute+tabla).
 */
export const EPISODE = {
  id: "05",
  slug: "yaksha-prashna",
  title: "Yaksha Prashna",
  subtitle: "The lake of questions",
  style: "cinematic-plates",
  stillsDir: "episodes/05-yaksha-prashna/stills/",
  voice: {
    provider: "local-kokoro",
    voice_id: "bm_george",
    cache: "ep05-kokoro-20261003",
    note: "Kathavachak — Kokoro-82M bm_george (free local, Apache-2.0, speed 0.9) via tools/render_local_voice.sh; no paid xAI API (SuperGrok-only rule). Files keep orion-NN.mp3 names/fingerprint (24 kHz / 128 kbps / mono / -16 LUFS).",
    base: "episodes/05-yaksha-prashna/audio/",
  },
  music: {
    raga: "bhairav",
    note: "Bhairav mandra tanpura; sparse bansuri; no tabla. Sacred lake / dharma questions. Duck under Orion. Not default flute+tabla.",
  },
  totalSec: 110,
  stills: {
    poster: "episodes/05-yaksha-prashna/stills/poster.jpg",
  },
  plates: {
    wide: "plate-wide.jpg",
    thirst: "plate-thirst.jpg",
    lake: "plate-lake.jpg",
    fall: "plate-fall.jpg",
    yudhi: "plate-yudhi.jpg",
    yaksha: "plate-yaksha.jpg",
    answers: "plate-answers.jpg",
    rise: "plate-rise.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  end: {
    title: "End of Episode 05",
    line: "Dharma is the highest wealth — and the lake yields to the one who knows it.",
    next: "play.html?ep=06",
    nextLabel: "Play Episode 06",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      audio: "orion-00.mp3",
      who: "Narrator",
      text: "Deep in the forest the Pandavas wander, weary from the long exile.",
    },
    {
      t: 12,
      plate: "thirst",
      zoom: 1.1,
      panX: 0.03,
      panY: -0.02,
      audio: "orion-01.mp3",
      who: "Narrator",
      text: "Thirst burns. Yudhishthira sends his brothers one by one to seek water.",
    },
    {
      t: 24,
      plate: "lake",
      zoom: 1.12,
      panX: 0,
      panY: -0.03,
      audio: "orion-02.mp3",
      who: "Narrator",
      text: "They find a still forest lake — clear as glass, and strangely silent.",
    },
    {
      t: 36,
      plate: "fall",
      zoom: 1.14,
      panX: -0.02,
      panY: 0,
      audio: "orion-03.mp3",
      who: "Narrator",
      text: "A voice warns: answer first, or do not drink. They drink. One by one they fall.",
    },
    {
      t: 48,
      plate: "yudhi",
      zoom: 1.12,
      panX: 0.04,
      panY: -0.02,
      audio: "orion-04.mp3",
      who: "Narrator",
      text: "Yudhishthira comes last, finds his brothers still as stone, and will not drink without leave.",
    },
    {
      t: 60,
      plate: "yaksha",
      zoom: 1.16,
      panX: 0.02,
      panY: -0.04,
      audio: "orion-05.mp3",
      who: "Narrator",
      text: "A yaksha appears upon the waters — luminous, stern, and endless with questions.",
    },
    {
      t: 72,
      plate: "answers",
      zoom: 1.18,
      panX: 0,
      panY: -0.02,
      audio: "orion-06.mp3",
      who: "Narrator",
      text: "What is heavier than earth? Mother. Higher than heaven? Father. Yudhishthira answers without fear.",
    },
    {
      t: 84,
      plate: "rise",
      zoom: 1.12,
      panX: 0.03,
      panY: 0,
      audio: "orion-07.mp3",
      who: "Narrator",
      text: "Asked whom to revive first, he names Nakula — equal love for both mothers. The yaksha is Dharma himself.",
    },
    {
      t: 96,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      audio: "orion-08.mp3",
      who: "Narrator",
      text: "So the lake taught what the war would ask: strength without dharma is only thirst.",
    },
    {
      t: 108,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
