/**
 * Episode 01 — The Bird's Eye
 * Ādi Parva · Drona's bhāsa-lakṣya test. Ep 09/10 canvas. Orion + Bhupali.
 */
export const EPISODE = {
  id: "01",
  slug: "birds-eye",
  title: "The Bird's Eye",
  subtitle: "Drona’s test of Arjuna",
  style: "cinematic-plates",
  stillsDir: "episodes/01-birds-eye/stills/",
  voice: {
    provider: "grok-tts",
    voice_id: "orion",
    cache: "ep01-orion",
    note: "Grok TTS orion — 24 kHz / 128 kbps",
    base: "episodes/01-birds-eye/audio/",
  },
  music: {
    raga: "bhupali",
    note: "Morning Bhupali tanpura + sparse bansuri; no tabla. Duck under Orion.",
  },
  totalSec: 102,
  stills: {
    poster: "episodes/01-birds-eye/stills/poster.jpg",
  },
  plates: {
    wide: "plate-wide.jpg",
    drona: "plate-drona.jpg",
    yudhishthira: "plate-yudhishthira.jpg",
    aside: "plate-aside.jpg",
    "arjuna-bow": "plate-arjuna-bow.jpg",
    eye: "plate-eye.jpg",
    loose: "plate-loose.jpg",
    release: "plate-release.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  end: {
    title: "End of Episode 01",
    line: "See the essential — and nothing else.",
    next: "play.html?ep=02",
    nextLabel: "Play Episode 02",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      audio: "orion-00.mp3",
      who: "Narrator",
      text: "In Hastināpura’s garden Drona tests the princes. An artisan’s bird sits high on a tree.",
    },
    {
      t: 11,
      plate: "drona",
      zoom: 1.12,
      panX: -0.04,
      panY: -0.02,
      audio: "orion-01.mp3",
      who: "Drona",
      text: "Take your bows. Aim at that bird. When I give the word, cut off its head.",
    },
    {
      t: 22,
      plate: "yudhishthira",
      zoom: 1.14,
      panX: 0.03,
      panY: 0,
      audio: "orion-02.mp3",
      who: "Yudhishthira",
      text: "I see the tree. I see you. I see my brothers. I see the bird.",
    },
    {
      t: 33,
      plate: "aside",
      zoom: 1.12,
      panX: -0.03,
      panY: 0,
      audio: "orion-03.mp3",
      who: "Drona",
      text: "This is not for you. Stand apart.",
    },
    {
      t: 44,
      plate: "arjuna-bow",
      zoom: 1.16,
      panX: 0.05,
      panY: -0.02,
      audio: "orion-04.mp3",
      who: "Narrator",
      text: "Then Arjuna stands with the bow drawn — waiting for the order.",
    },
    {
      t: 55,
      plate: "eye",
      zoom: 1.28,
      panX: 0,
      panY: -0.04,
      audio: "orion-05.mp3",
      who: "Arjuna",
      text: "I see only the head of the bird, Acharya. Not the tree. Not you.",
    },
    {
      t: 66,
      plate: "loose",
      zoom: 1.14,
      panX: -0.02,
      panY: 0,
      audio: "orion-06.mp3",
      who: "Drona",
      text: "Shoot.",
    },
    {
      t: 74,
      plate: "release",
      zoom: 1.18,
      panX: 0.04,
      panY: -0.03,
      audio: "orion-07.mp3",
      who: "Narrator",
      text: "The shaft takes the bird’s head. Gold dust on the grass — no blood.",
    },
    {
      t: 88,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      audio: "orion-08.mp3",
      who: "Narrator",
      text: "Drona holds him close. The aim is one thought.",
    },
    {
      t: 100,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
