/**
 * Episode 01 — The Bird's Eye
 * Natural dialogue + Grok TTS (orion) pre-rendered audio.
 * Plates/animation timing unchanged.
 */
export const EPISODE = {
  id: "01",
  slug: "birds-eye",
  title: "The Bird's Eye",
  subtitle: "Drona’s test of Arjuna",
  style: "cinematic-plates",
  stillsDir: "episodes/01-birds-eye/stills/",
  voice: {
    provider: "grok-tts",
    voice_id: "orion",
    cache: "nofeather1",
    note: "Deep heroic male Grok voice (orion). Files: orion-NN.mp3",
    base: "episodes/01-birds-eye/audio/",
  },
  totalSec: 88,
  stills: {
    poster: "episodes/01-birds-eye/stills/poster.jpg",
    garden: "episodes/01-birds-eye/stills/garden-plate.jpg",
  },
  end: {
    title: "End of Episode 01",
    line: "See the essential — and nothing else.",
    next: "play.html?ep=02",
    nextLabel: "Play Episode 02",
  },
  plates: {
    wide: "plate-wide.jpg",
    drona: "plate-drona.jpg",
    princes: "plate-princes.jpg",
    bird: "plate-bird.jpg",
    "arjuna-bow": "plate-arjuna-bow.jpg",
    eye: "plate-eye.jpg",
    release: "plate-release.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      audio: "orion-00.mp3",
      who: "Narrator",
      text: "In the gardens of Hastināpura, Guru Drona calls the princes for a simple test.",
    },
    {
      t: 8,
      plate: "drona",
      zoom: 1.12,
      panX: -0.05,
      panY: -0.02,
      audio: "orion-01.mp3",
      who: "Drona",
      text: "There — on that tree. A bird. String your bows. Tell me what you see.",
    },
    {
      t: 16,
      plate: "princes",
      zoom: 1.1,
      panX: 0.04,
      panY: 0,
      audio: "orion-02.mp3",
      who: "Narrator",
      text: "One after another, the princes answer. Each sees more than he should.",
    },
    {
      t: 24,
      plate: "bird",
      zoom: 1.2,
      panX: 0.08,
      panY: -0.06,
      audio: "orion-03.mp3",
      who: "Prince",
      text: "I see the bird… and the branch… and the sky behind it.",
    },
    {
      t: 32,
      plate: "drona",
      zoom: 1.15,
      panX: -0.04,
      panY: 0,
      audio: "orion-04.mp3",
      who: "Drona",
      text: "Not enough. Step aside.",
    },
    {
      t: 38,
      plate: "arjuna-bow",
      zoom: 1.14,
      panX: 0.06,
      panY: 0,
      audio: "orion-05.mp3",
      who: "Narrator",
      text: "Then Arjuna steps forward, draws the bowstring to his ear, and steadies his breath.",
    },
    {
      t: 46,
      plate: "arjuna-bow",
      zoom: 1.28,
      panX: 0.08,
      panY: -0.04,
      audio: "orion-06.mp3",
      who: "Drona",
      text: "Arjuna. What do you see?",
    },
    {
      t: 52,
      plate: "eye",
      zoom: 1.35,
      panX: 0,
      panY: 0,
      audio: "orion-07.mp3",
      who: "Arjuna",
      text: "Only the eye of the bird, Acharya. Nothing else.",
    },
    {
      t: 60,
      plate: "eye",
      zoom: 1.5,
      panX: 0,
      panY: 0,
      audio: "orion-08.mp3",
      who: "Drona",
      text: "Then loose.",
    },
    {
      t: 66,
      plate: "release",
      zoom: 1.18,
      panX: 0.05,
      panY: -0.03,
      audio: "orion-09.mp3",
      who: "Narrator",
      text: "The arrow flies true and strikes the mark. That is how a warrior aims — with one clear thought.",
    },
    {
      t: 76,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      audio: "orion-10.mp3",
      who: "Narrator",
      text: "And Arjuna never forgot it: see the essential — and nothing else.",
    },
    {
      t: 86,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
