/**
 * Episode 01 — The Bird's Eye
 * Cinematic plate animation (painterly plates matching garden aesthetic).
 * Beats: plate key, ken-burns focus, dialogue.
 */
export const EPISODE = {
  id: "01",
  title: "The Bird's Eye",
  subtitle: "Drona’s test of Arjuna",
  style: "cinematic-plates",
  totalSec: 88,
  stills: {
    poster: "episodes/01-birds-eye/stills/poster.jpg",
    garden: "episodes/01-birds-eye/stills/garden-plate.jpg",
  },
  /** Named plates under episodes/01-birds-eye/stills/ */
  plates: {
    wide: "plate-wide.jpg",
    drona: "plate-drona.jpg",
    princes: "plate-princes.jpg",
    bird: "plate-bird.jpg",
    "arjuna-bow": "plate-arjuna-bow.jpg",
    eye: "plate-eye.jpg",
    release: "plate-release.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      who: "Narrator",
      text: "In the gardens of Hastināpura, the Acharya sets a test no prince will forget.",
    },
    {
      t: 8,
      plate: "drona",
      zoom: 1.12,
      panX: -0.05,
      panY: -0.02,
      who: "Drona",
      text: "There — a bird upon the tree. Fix an arrow. Tell me what you see.",
    },
    {
      t: 16,
      plate: "princes",
      zoom: 1.1,
      panX: 0.04,
      panY: 0,
      who: "Narrator",
      text: "One by one they speak of leaves, of sky, of feathers catching light.",
    },
    {
      t: 24,
      plate: "bird",
      zoom: 1.2,
      panX: 0.08,
      panY: -0.06,
      who: "Prince",
      text: "I see the bird, the branch, the cloud behind it…",
    },
    {
      t: 32,
      plate: "drona",
      zoom: 1.15,
      panX: -0.04,
      panY: 0,
      who: "Drona",
      text: "Not enough. Step aside.",
    },
    {
      t: 38,
      plate: "arjuna-bow",
      zoom: 1.14,
      panX: 0.06,
      panY: 0,
      who: "Narrator",
      text: "Then Arjuna raises the bow. The world narrows.",
    },
    {
      t: 46,
      plate: "arjuna-bow",
      zoom: 1.28,
      panX: 0.08,
      panY: -0.04,
      who: "Drona",
      text: "What do you see, Arjuna?",
    },
    {
      t: 52,
      plate: "eye",
      zoom: 1.35,
      panX: 0,
      panY: 0,
      who: "Arjuna",
      text: "I see only the eye of the bird.",
    },
    {
      t: 60,
      plate: "eye",
      zoom: 1.5,
      panX: 0,
      panY: 0,
      who: "Drona",
      text: "Loose.",
    },
    {
      t: 66,
      plate: "release",
      zoom: 1.18,
      panX: 0.05,
      panY: -0.03,
      who: "Narrator",
      text: "The arrow flies true. Concentration is the first dharma of the warrior.",
    },
    {
      t: 76,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      who: "Narrator",
      text: "Thus the son of Indra learned: see the essential — and nothing else.",
    },
    {
      t: 86,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
