/**
 * Episode 09 — The Gita
 * Bhishma Parva · Kurukshetra · Arjuna’s despair · Krishna’s counsel
 */
export const EPISODE = {
  id: "09",
  slug: "gita",
  title: "The Gita",
  subtitle: "Counsel on the field of dharma",
  style: "cinematic-plates",
  stillsDir: "episodes/09-gita/stills/",
  voice: {
    provider: "grok-tts",
    voice_id: "orion",
    cache: "ep09-v1",
    note: "Grok TTS orion — deep heroic narration",
    base: "episodes/09-gita/audio/",
  },
  totalSec: 104,
  stills: {
    poster: "episodes/09-gita/stills/poster.jpg",
  },
  plates: {
    wide: "plate-wide.jpg",
    armies: "plate-armies.jpg",
    chariot: "plate-chariot.jpg",
    despair: "plate-despair.jpg",
    counsel: "plate-counsel.jpg",
    self: "plate-self.jpg",
    form: "plate-form.jpg",
    rise: "plate-rise.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  end: {
    title: "End of Episode 09",
    line: "Do your duty — and leave the fruit to dharma.",
    next: "index.html",
    nextLabel: "All episodes",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      audio: "orion-00.mp3",
      who: "Narrator",
      text: "On the field of Kurukshetra the two oceans of war face each other at dawn.",
    },
    {
      t: 10,
      plate: "armies",
      zoom: 1.1,
      panX: 0.03,
      panY: -0.02,
      audio: "orion-01.mp3",
      who: "Narrator",
      text: "Conches sound. Banners lift. Kin stand ready to strike kin.",
    },
    {
      t: 20,
      plate: "chariot",
      zoom: 1.14,
      panX: -0.02,
      panY: -0.03,
      audio: "orion-02.mp3",
      who: "Narrator",
      text: "Arjuna asks Krishna to drive between the hosts — to see those he must fight.",
    },
    {
      t: 32,
      plate: "despair",
      zoom: 1.18,
      panX: 0.02,
      panY: -0.04,
      audio: "orion-03.mp3",
      who: "Narrator",
      text: "His bow slips. Teachers, cousins, friends — his heart collapses into grief.",
    },
    {
      t: 44,
      plate: "counsel",
      zoom: 1.16,
      panX: 0,
      panY: -0.02,
      audio: "orion-04.mp3",
      who: "Narrator",
      text: "Krishna speaks: the soul is not slain; the body is only a garment.",
    },
    {
      t: 56,
      plate: "self",
      zoom: 1.14,
      panX: 0.03,
      panY: -0.02,
      audio: "orion-05.mp3",
      who: "Narrator",
      text: "Act without clinging to the fruit. Stand in your dharma as a warrior.",
    },
    {
      t: 68,
      plate: "form",
      zoom: 1.22,
      panX: 0.02,
      panY: -0.05,
      audio: "orion-06.mp3",
      who: "Narrator",
      text: "Then Krishna shows the cosmic form — time itself devouring worlds.",
    },
    {
      t: 80,
      plate: "rise",
      zoom: 1.14,
      panX: -0.02,
      panY: 0,
      audio: "orion-07.mp3",
      who: "Narrator",
      text: "Arjuna’s confusion burns away. He takes up the bow again.",
    },
    {
      t: 92,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      audio: "orion-08.mp3",
      who: "Narrator",
      text: "So the song of the Lord was sung between two armies — and the war of ages began.",
    },
    {
      t: 102,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
