/**
 * Episode 09 — The Bhagavad Gita
 * Bhishma Parva · Kurukshetra opens; Krishna’s teaching to Arjuna
 */
export const EPISODE = {
  id: "09",
  slug: "gita",
  title: "The Bhagavad Gita",
  subtitle: "Kurukshetra opens",
  style: "cinematic-plates",
  stillsDir: "episodes/09-gita/stills/",
  voice: {
    provider: "grok-tts",
    voice_id: "orion",
    cache: "ep09-v1",
    note: "Grok TTS orion — deep heroic narration",
    base: "episodes/09-gita/audio/",
  },
  music: {
    raga: "bhairav",
    note: "Dawn Bhairav tanpura + sparse bansuri; no tabla. Duck under Orion.",
  },
  totalSec: 104,
  stills: {
    poster: "episodes/09-gita/stills/poster.jpg",
  },
  plates: {
    wide: "plate-wide.jpg",
    field: "plate-field.jpg",
    despair: "plate-despair.jpg",
    counsel: "plate-counsel.jpg",
    dharma: "plate-dharma.jpg",
    form: "plate-form.jpg",
    resolve: "plate-resolve.jpg",
    conch: "plate-conch.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  end: {
    title: "End of Episode 09",
    line: "When the bow is lifted again, the song of dharma has begun.",
    next: "index.html",
    nextLabel: "All episodes",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      audio: "orion-00.mp3",
      who: "Narrator",
      text: "On the field of Kurukshetra two oceans of men stand ready — kin against kin.",
    },
    {
      t: 11,
      plate: "field",
      zoom: 1.12,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-01.mp3",
      who: "Narrator",
      text: "Arjuna asks Krishna to drive between the armies, that he may see whom he must face.",
    },
    {
      t: 23,
      plate: "despair",
      zoom: 1.14,
      panX: -0.02,
      panY: -0.03,
      audio: "orion-02.mp3",
      who: "Narrator",
      text: "He sees teachers, cousins, friends — and his bow Gandiva slips from his hands.",
    },
    {
      t: 35,
      plate: "counsel",
      zoom: 1.16,
      panX: 0.03,
      panY: -0.02,
      audio: "orion-03.mp3",
      who: "Narrator",
      text: "Grief shakes the great archer. Krishna, calm as the sky, begins to speak.",
    },
    {
      t: 47,
      plate: "dharma",
      zoom: 1.14,
      panX: 0,
      panY: -0.02,
      audio: "orion-04.mp3",
      who: "Narrator",
      text: "He teaches of the soul that is never slain, of duty without clinging to fruit.",
    },
    {
      t: 59,
      plate: "form",
      zoom: 1.2,
      panX: 0.02,
      panY: -0.04,
      audio: "orion-05.mp3",
      who: "Narrator",
      text: "At Arjuna’s prayer he shows the cosmic form — a universe of light upon the chariot.",
    },
    {
      t: 71,
      plate: "resolve",
      zoom: 1.14,
      panX: -0.02,
      panY: 0,
      audio: "orion-06.mp3",
      who: "Narrator",
      text: "Doubt falls away. Arjuna takes up his bow again, mind steady in dharma.",
    },
    {
      t: 83,
      plate: "conch",
      zoom: 1.12,
      panX: 0.03,
      panY: -0.02,
      audio: "orion-07.mp3",
      who: "Narrator",
      text: "Conches sound across the field. The song is sung — and the war of ages begins.",
    },
    {
      t: 94,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      audio: "orion-08.mp3",
      who: "Narrator",
      text: "Thus on Kurukshetra the Bhagavad Gita was spoken — light before the storm.",
    },
    {
      t: 102,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
