/**
 * Episode 12 — Jayadratha Falls
 * Drona Parva · fourteenth day; Arjuna’s vow; the false dusk
 */
export const EPISODE = {
  id: "12",
  slug: "jayadratha-vadha",
  title: "Jayadratha Falls",
  subtitle: "Fourteenth day of Kurukshetra",
  style: "cinematic-plates",
  stillsDir: "episodes/12-jayadratha-vadha/stills/",
  voice: {
    provider: "grok-tts",
    voice_id: "orion",
    cache: "ep12-orion",
    note: "Kathavachak — grok-tts Orion (same pipeline as Ep 09–11)",
    base: "episodes/12-jayadratha-vadha/audio/",
  },
  music: {
    raga: "marwa",
    note: "Sunset Marwa tanpura + sparse bansuri; no Pa, no tabla. Duck under Orion.",
  },
  totalSec: 104,
  stills: {
    poster: "episodes/12-jayadratha-vadha/stills/poster.jpg",
  },
  plates: {
    wide: "plate-wide.jpg",
    vow: "plate-vow.jpg",
    wall: "plate-wall.jpg",
    hunt: "plate-hunt.jpg",
    dusk: "plate-dusk.jpg",
    veil: "plate-veil.jpg",
    reveal: "plate-reveal.jpg",
    shaft: "plate-shaft.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  end: {
    title: "End of Episode 12",
    line: "The vow is kept. The sun goes down on a word that held.",
    next: "index.html",
    nextLabel: "All episodes",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      audio: "orion-00.mp3",
      who: "Narrator",
      text: "Dawn of the fourteenth. Arjuna’s vow hangs over the field: Jayadratha dies before sunset, or I do.",
    },
    {
      t: 12,
      plate: "vow",
      zoom: 1.14,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-01.mp3",
      who: "Narrator",
      text: "Krishna takes the reins. They drive into the host — the Sindhu king is hidden behind a wall of men.",
    },
    {
      t: 24,
      plate: "wall",
      zoom: 1.12,
      panX: -0.02,
      panY: -0.02,
      audio: "orion-02.mp3",
      who: "Narrator",
      text: "Drona holds that wall. Jayadratha waits in the rear, beyond every gold shaft.",
    },
    {
      t: 36,
      plate: "hunt",
      zoom: 1.14,
      panX: 0.03,
      panY: -0.02,
      audio: "orion-03.mp3",
      who: "Narrator",
      text: "Krishna cuts a path. Arjuna’s arrows clear the ranks — and still the king of Sindhu is not seen.",
    },
    {
      t: 48,
      plate: "dusk",
      zoom: 1.16,
      panX: 0,
      panY: -0.03,
      audio: "orion-04.mp3",
      who: "Narrator",
      text: "The sun leans west. The vow grows thin. Jayadratha still lives.",
    },
    {
      t: 60,
      plate: "veil",
      zoom: 1.18,
      panX: 0.02,
      panY: -0.04,
      audio: "orion-05.mp3",
      who: "Narrator",
      text: "Krishna raises his disc. A false dusk covers the field — and Jayadratha comes forth to laugh.",
    },
    {
      t: 72,
      plate: "reveal",
      zoom: 1.16,
      panX: -0.02,
      panY: -0.02,
      audio: "orion-06.mp3",
      who: "Narrator",
      text: "The disc falls. The sun still stands. The Sindhu king is exposed.",
    },
    {
      t: 84,
      plate: "shaft",
      zoom: 1.14,
      panX: 0.02,
      panY: 0.02,
      audio: "orion-07.mp3",
      who: "Narrator",
      text: "Arjuna looses. The arrow carries the crowned head as gold light into his father’s lap.",
    },
    {
      t: 95,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      audio: "orion-08.mp3",
      who: "Narrator",
      text: "Thus the fourteenth day ends. Jayadratha falls — and a kept word outlives the sun.",
    },
    {
      t: 102,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
