/**
 * Episode 13 — Ghatotkacha
 * Drona Parva · night of the fourteenth; Karna’s Shakti
 */
export const EPISODE = {
  id: "13",
  slug: "ghatotkacha",
  title: "Ghatotkacha",
  subtitle: "Night of the fourteenth",
  style: "cinematic-plates",
  stillsDir: "episodes/13-ghatotkacha/stills/",
  voice: {
    provider: "grok-tts",
    voice_id: "orion",
    cache: "ep13-orion",
    note: "Kathavachak — grok-tts Orion (same pipeline as Ep 09–12)",
    base: "episodes/13-ghatotkacha/audio/",
  },
  music: {
    raga: "malkauns",
    note: "Midnight Malkauns tanpura + sparse bansuri; no Re, no Pa, no tabla. Duck under Orion.",
  },
  totalSec: 104,
  stills: {
    poster: "episodes/13-ghatotkacha/stills/poster.jpg",
  },
  plates: {
    wide: "plate-wide.jpg",
    plea: "plate-plea.jpg",
    storm: "plate-storm.jpg",
    counsel: "plate-counsel.jpg",
    dart: "plate-dart.jpg",
    loose: "plate-loose.jpg",
    fall: "plate-fall.jpg",
    hush: "plate-hush.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  end: {
    title: "End of Episode 13",
    line: "The dart is spent. Morning will come for Drona.",
    next: "index.html",
    nextLabel: "All episodes",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      audio: "orion-00.mp3",
      who: "Narrator",
      text: "Night after the vow. Bhima’s son Ghatotkacha darkens the field — a rakshasa-prince grown for this hour.",
    },
    {
      t: 12,
      plate: "plea",
      zoom: 1.14,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-01.mp3",
      who: "Narrator",
      text: "Duryodhana finds Karna: the night is eating the host — use the dart, or we are lost.",
    },
    {
      t: 24,
      plate: "storm",
      zoom: 1.12,
      panX: -0.02,
      panY: -0.02,
      audio: "orion-02.mp3",
      who: "Narrator",
      text: "Illusions wheel over the Kauravas: elephants of mist, a storm of banners — no blood.",
    },
    {
      t: 36,
      plate: "counsel",
      zoom: 1.14,
      panX: 0.03,
      panY: -0.02,
      audio: "orion-03.mp3",
      who: "Narrator",
      text: "Krishna, calm at the reins, knows the dart that was kept for Arjuna.",
    },
    {
      t: 48,
      plate: "dart",
      zoom: 1.16,
      panX: 0,
      panY: -0.03,
      audio: "orion-04.mp3",
      who: "Narrator",
      text: "Karna lifts the Vasavi Shakti — one bolt, given by Indra, never twice.",
    },
    {
      t: 60,
      plate: "loose",
      zoom: 1.18,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-05.mp3",
      who: "Narrator",
      text: "He looses. A single gold shaft of light finds the rakshasa-prince.",
    },
    {
      t: 72,
      plate: "fall",
      zoom: 1.12,
      panX: -0.02,
      panY: 0.02,
      audio: "orion-06.mp3",
      who: "Narrator",
      text: "Ghatotkacha falls as a mountain falls — and the night thins.",
    },
    {
      t: 84,
      plate: "hush",
      zoom: 1.14,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-07.mp3",
      who: "Narrator",
      text: "The dart is spent. Arjuna lives. The fourteenth night keeps a deeper vow.",
    },
    {
      t: 95,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      audio: "orion-08.mp3",
      who: "Narrator",
      text: "Thus Karna’s greatest weapon is gone — and morning will come for Drona.",
    },
    {
      t: 102,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
