#!/usr/bin/env python3
"""
Import SuperGrok consumer / browser Imagine stills into an episode stills tree.

When XAI_API_KEY team credits are blocked, operators generate beat plates on
grok.com Imagine (with lock refs), download them, drop into the episode inbox,
then run this tool to rename/copy into GATE C layout.

Inbox convention (preferred):
  episodes/<id>/stills/_inbox/consumer-imagine/

Optional alternate (also accepted if --inbox points there):
  stills/_inbox/consumer-imagine/<ep-id>/   (repo-root relative under tools caller)

Usage:
  python3 tools/import_consumer_stills.py 03-bhima-bakasura
  python3 tools/import_consumer_stills.py 03-bhima-bakasura \\
      --inbox episodes/03-bhima-bakasura/stills/_inbox/consumer-imagine
  python3 tools/import_consumer_stills.py 03-bhima-bakasura --map map.json
  python3 tools/import_consumer_stills.py 03-bhima-bakasura --dry-run

Map JSON keys → source filenames in the inbox (or absolute/relative paths):
  {
    "wide": "IMG_001.png",
    "terror": "terror-regen.jpg",
    "poster": "clash-copy.jpg",
    "_locks/bhima": "bhima-lock.jpg"
  }

Without --map, files already named plate-*.jpg / poster.jpg / lock files under
_locks/ (or lock-<id>.jpg) are imported by name.
"""
from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from stills_review import jpeg_wh, ok_size  # noqa: E402

IMAGE_EXTS = {".jpg", ".jpeg", ".png", ".webp"}
WATERMARK_MARKERS = (
    b"grok",
    b"Grok",
    b"GROK",
    b"xAI",
    b"xai.com",
    b"grok.com",
    b"Made with Grok",
    b"generated by grok",
)


def default_inbox(ep_id: str) -> Path:
    return ROOT / "episodes" / ep_id / "stills" / "_inbox" / "consumer-imagine"


def resolve_ep(ep_arg: str) -> tuple[str, Path]:
    p = Path(ep_arg)
    if p.is_dir() and (p / "stills").is_dir():
        ep_dir = p if p.is_absolute() else (ROOT / p).resolve()
        return ep_dir.name, ep_dir
    # bare id
    ep_id = ep_arg.strip().rstrip("/")
    if ep_id.startswith("episodes/"):
        ep_id = ep_id.split("/", 1)[1]
    ep_dir = ROOT / "episodes" / ep_id
    return ep_id, ep_dir


def normalize_dest_key(key: str) -> str:
    """Return relative dest under stills/ (e.g. plate-wide.jpg, _locks/bhima.jpg, poster.jpg)."""
    k = key.strip().replace("\\", "/")
    if k.startswith("stills/"):
        k = k[len("stills/") :]
    if k.startswith("plate-") and Path(k).suffix.lower() in IMAGE_EXTS | {""}:
        stem = Path(k).stem
        return f"{stem}.jpg" if stem.startswith("plate-") else f"plate-{stem}.jpg"
    if k in {"poster", "poster.jpg", "poster.jpeg"}:
        return "poster.jpg"
    if k.startswith("_locks/") or k.startswith("locks/"):
        name = Path(k).name
        stem = Path(name).stem
        if stem.startswith("lock-"):
            stem = stem[5:]
        return f"_locks/{stem}.jpg"
    if k.startswith("lock-"):
        stem = Path(k).stem[5:]
        return f"_locks/{stem}.jpg"
    # bare beat name: wide → plate-wide.jpg
    stem = Path(k).stem if Path(k).suffix else k
    if stem.startswith("plate-"):
        return f"{stem}.jpg"
    return f"plate-{stem}.jpg"


def discover_named(inbox: Path) -> dict[str, Path]:
    """Auto-map plate-*.jpg, poster.*, lock-*.*, and _locks/* from inbox."""
    mapping: dict[str, Path] = {}
    if not inbox.is_dir():
        return mapping
    for p in sorted(inbox.rglob("*")):
        if not p.is_file() or p.name.startswith("."):
            continue
        if p.suffix.lower() not in IMAGE_EXTS:
            continue
        # skip nested junk under other folders except _locks
        rel = p.relative_to(inbox)
        parts = rel.parts
        if any(part.startswith("_") and part not in {"_locks"} for part in parts[:-1]):
            continue
        name = p.name
        low = name.lower()
        if low.startswith("plate-") or low.startswith("poster."):
            key = Path(name).stem if low.startswith("plate-") else "poster"
            mapping[normalize_dest_key(key)] = p
        elif low.startswith("lock-"):
            mapping[normalize_dest_key(name)] = p
        elif len(parts) >= 2 and parts[0] == "_locks":
            mapping[normalize_dest_key(f"_locks/{name}")] = p
    return mapping


def load_map(map_path: Path, inbox: Path) -> dict[str, Path]:
    data = json.loads(map_path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise SystemExit("FAIL: --map JSON must be an object of plate-key → filename")
    out: dict[str, Path] = {}
    for key, fname in data.items():
        dest = normalize_dest_key(str(key))
        src = Path(str(fname))
        if not src.is_absolute():
            cand = inbox / src
            if cand.exists():
                src = cand
            else:
                src = (ROOT / src).resolve() if (ROOT / src).exists() else cand
        out[dest] = src
    return out


def ensure_jpeg(src: Path, tmp_dir: Path) -> Path:
    """Return a JPEG path; convert PNG/WEBP via sips when needed."""
    suf = src.suffix.lower()
    if suf in {".jpg", ".jpeg"}:
        return src
    tmp_dir.mkdir(parents=True, exist_ok=True)
    out = tmp_dir / (src.stem + ".jpg")
    # macOS sips
    try:
        subprocess.run(
            ["sips", "-s", "format", "jpeg", str(src), "--out", str(out)],
            check=True,
            capture_output=True,
            text=True,
        )
    except (subprocess.CalledProcessError, FileNotFoundError) as e:
        raise SystemExit(
            f"FAIL: cannot convert {src.name} to JPEG (need sips on macOS): {e}"
        ) from e
    if not out.exists():
        raise SystemExit(f"FAIL: sips produced no output for {src}")
    return out


def watermark_hits(path: Path) -> list[str]:
    """Heuristic: scan file bytes / APP markers for obvious Grok watermark strings."""
    hits: list[str] = []
    data = path.read_bytes()
    # Limit scan cost on huge files
    sample = data if len(data) < 12_000_000 else (data[:2_000_000] + data[-500_000:])
    lower = sample.lower()
    for marker in WATERMARK_MARKERS:
        if marker.lower() in lower:
            hits.append(marker.decode("utf-8", errors="replace"))
    # EXIF/XMP-ish ASCII
    for m in re.finditer(rb"[\x20-\x7e]{8,120}", sample):
        s = m.group().decode("ascii", errors="ignore")
        sl = s.lower()
        if "grok" in sl and ("watermark" in sl or "imagine" in sl or "xai" in sl):
            hits.append(s.strip()[:80])
    # dedupe
    seen: set[str] = set()
    uniq: list[str] = []
    for h in hits:
        if h not in seen:
            seen.add(h)
            uniq.append(h)
    return uniq


def check_dims(jpeg_path: Path) -> list[str]:
    w, h = jpeg_wh(jpeg_path)
    return ok_size(w, h)


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Import SuperGrok consumer Imagine stills into episodes/<id>/stills/"
    )
    ap.add_argument(
        "episode",
        help="episode id (e.g. 03-bhima-bakasura) or path to episodes/<id>",
    )
    ap.add_argument(
        "--inbox",
        type=Path,
        default=None,
        help="drop folder (default: episodes/<id>/stills/_inbox/consumer-imagine/)",
    )
    ap.add_argument(
        "--map",
        type=Path,
        default=None,
        help="optional JSON map: plate-key → filename in inbox",
    )
    ap.add_argument(
        "--dry-run",
        action="store_true",
        help="print actions without copying",
    )
    ap.add_argument(
        "--force",
        action="store_true",
        help="overwrite existing stills targets",
    )
    ap.add_argument(
        "--allow-watermark",
        action="store_true",
        help="do not fail when watermark heuristic fires (still prints warning)",
    )
    args = ap.parse_args()

    ep_id, ep_dir = resolve_ep(args.episode)
    if not ep_dir.is_dir():
        print(f"FAIL: missing episode dir {ep_dir}", file=sys.stderr)
        return 2

    stills = ep_dir / "stills"
    stills.mkdir(parents=True, exist_ok=True)
    inbox = args.inbox if args.inbox is not None else default_inbox(ep_id)
    if not inbox.is_absolute():
        inbox = (ROOT / inbox).resolve()

    if args.map:
        map_path = args.map if args.map.is_absolute() else (ROOT / args.map)
        mapping = load_map(map_path, inbox)
    else:
        mapping = discover_named(inbox)

    if not mapping:
        print(f"FAIL: no importable stills in {inbox}")
        print("  Drop plate-*.jpg / poster.jpg / lock-<id>.jpg there, or pass --map JSON.")
        print("  See docs/CONSUMER_IMAGINE_IMPORT.md")
        return 1

    tmp_dir = stills / "_inbox" / ".tmp_convert"
    errors: list[str] = []
    imported: list[str] = []

    print(f"episode: {ep_id}")
    print(f"inbox:   {inbox}")
    print(f"targets: {len(mapping)}")
    print()

    for dest_rel, src in sorted(mapping.items()):
        if not src.exists():
            errors.append(f"missing source for {dest_rel}: {src}")
            continue
        try:
            jpeg_src = ensure_jpeg(src, tmp_dir)
        except SystemExit as e:
            errors.append(str(e))
            continue

        try:
            dim_fails = check_dims(jpeg_src)
        except ValueError as e:
            errors.append(f"{dest_rel}: {e}")
            continue
        if dim_fails:
            for reason in dim_fails:
                errors.append(f"{dest_rel} ({src.name}): {reason}")
            continue

        wm = watermark_hits(jpeg_src)
        if wm:
            msg = f"{dest_rel}: possible Grok watermark markers in file bytes: {wm[:3]}"
            if args.allow_watermark:
                print(f"WARN  {msg}")
            else:
                errors.append(msg + " (re-export without watermark, or pass --allow-watermark after eye-check)")
                continue

        dest = stills / dest_rel
        if dest.exists() and not args.force and not args.dry_run:
            errors.append(f"{dest_rel}: exists (pass --force to overwrite)")
            continue

        w, h = jpeg_wh(jpeg_src)
        action = "would copy" if args.dry_run else "copy"
        print(f"  {action}: {src.name} → stills/{dest_rel}  ({w}×{h})")
        if not args.dry_run:
            dest.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(jpeg_src, dest)
        imported.append(dest_rel)

    # cleanup tmp converts
    if tmp_dir.exists() and not args.dry_run:
        shutil.rmtree(tmp_dir, ignore_errors=True)

    print()
    if errors:
        print("FAIL")
        for e in errors:
            print(f"  - {e}")
        if imported:
            print(f"  (partial: {len(imported)} file(s) staged before errors)")
        return 1

    print(f"OK  imported {len(imported)} file(s)")
    print()
    print("Next steps:")
    print(f"  1. Eye-check corners for Grok watermark (heuristic is not enough).")
    print(f"  2. python3 tools/stills_review.py episodes/{ep_id} --require")
    print(f"  3. Fill episodes/{ep_id}/logic-reviews/RR-gateC-visual.md from docs/GATE_C_TEMPLATE.md")
    print(f"  4. On GATE C PASS → publish path (registry / commit / publish-pages)")
    print()
    print("Note: scene master + cast locks still prefer beauty pass on grok.com or Imagine API.")
    print("Never use Ep01 plate-wide-gold as a ref. No 720p. Bar stays ≥1536×1024 3:2.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
