/**
 * Episode 03 — Bhima and Bakasura
 * Ekachakra · the rakshasa’s due · cinematic plates + Orion TTS + flute/tabla.
 */
export const EPISODE = {
  id: "03",
  slug: "bhima-bakasura",
  title: "Bhima and Bakasura",
  subtitle: "The terror of Ekachakra",
  style: "cinematic-plates",
  stillsDir: "episodes/03-bhima-bakasura/stills/",
  voice: {
    provider: "grok-tts",
    voice_id: "orion",
    cache: "ep03-v1",
    note: "Grok TTS orion — deep heroic narration",
    base: "episodes/03-bhima-bakasura/audio/",
  },
  totalSec: 100,
  stills: {
    poster: "episodes/03-bhima-bakasura/stills/poster.jpg",
  },
  plates: {
    wide: "plate-wide.jpg",
    terror: "plate-terror.jpg",
    family: "plate-family.jpg",
    kunti: "plate-kunti.jpg",
    cart: "plate-cart.jpg",
    feast: "plate-feast.jpg",
    clash: "plate-clash.jpg",
    victory: "plate-victory.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  end: {
    title: "End of Episode 03",
    line: "Strength in service of the helpless is dharma.",
    next: "play.html?ep=04",
    nextLabel: "Play Episode 04",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      audio: "orion-00.mp3",
      who: "Narrator",
      text: "In the town of Ekachakra the Pandavas live in secret — and a shadow hangs over every home.",
    },
    {
      t: 10,
      plate: "terror",
      zoom: 1.12,
      panX: 0.03,
      panY: -0.02,
      audio: "orion-01.mp3",
      who: "Narrator",
      text: "Bakasura, a terrible rakshasa, demands a cart of food and one human life each day.",
    },
    {
      t: 22,
      plate: "family",
      zoom: 1.1,
      panX: -0.02,
      panY: 0,
      audio: "orion-02.mp3",
      who: "Narrator",
      text: "When the lot falls on a brahmin household, grief fills the cottage.",
    },
    {
      t: 32,
      plate: "kunti",
      zoom: 1.14,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-03.mp3",
      who: "Narrator",
      text: "Kunti hears their sorrow. She sends her son Bhima in their place.",
    },
    {
      t: 42,
      plate: "cart",
      zoom: 1.1,
      panX: 0.04,
      panY: 0,
      audio: "orion-04.mp3",
      who: "Narrator",
      text: "Bhima drives the food cart toward the forest, calm as a mountain on the move.",
    },
    {
      t: 52,
      plate: "feast",
      zoom: 1.16,
      panX: 0,
      panY: -0.03,
      audio: "orion-05.mp3",
      who: "Narrator",
      text: "He sits and eats every last morsel — then waits for the monster who would claim him.",
    },
    {
      t: 64,
      plate: "clash",
      zoom: 1.2,
      panX: 0.03,
      panY: -0.04,
      audio: "orion-06.mp3",
      who: "Narrator",
      text: "Bakasura comes roaring. Bhima meets him with bare hands and a warrior’s joy.",
    },
    {
      t: 76,
      plate: "victory",
      zoom: 1.18,
      panX: 0,
      panY: -0.02,
      audio: "orion-07.mp3",
      who: "Narrator",
      text: "The fight ends. Bakasura falls. Ekachakra will fear him no more.",
    },
    {
      t: 88,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      audio: "orion-08.mp3",
      who: "Narrator",
      text: "So Bhima kept the vow of the strong: protect those who cannot protect themselves.",
    },
    {
      t: 98,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
