/**
 * Solar system body catalog.
 * Periods: sidereal Earth days. Distances: AU (visual scale applied in main.js).
 * Orbits: Keplerian ellipse in the ecliptic with published inclinations.
 */
import {
  EARTH_MOONS,
  MARS_MOONS,
  JUPITER_MOONS,
  SATURN_MOONS,
  URANUS_MOONS,
  NEPTUNE_MOONS,
  PLUTO_MOONS,
  moonCountLabel,
} from "./moons.js";

export const SUN = {
  id: "sun",
  name: "Sol",
  type: "Star",
  color: 0xffc857,
  emissive: 0xffaa22,
  radiusKm: 695700,
  visualRadius: 2.8,
  blurb: "G2V main-sequence star — 99.8% of the system’s mass, powering every orbit.",
  stats: {
    Radius: "695,700 km",
    Mass: "1 M☉",
    Type: "G2V",
    Temp: "5,772 K",
  },
};

export const PLANETS = [
  {
    id: "mercury",
    name: "Mercury",
    type: "Terrestrial",
    color: 0xb1b1b1,
    radiusKm: 2439.7,
    visualRadius: 0.28,
    a_au: 0.387,
    periodDays: 87.969,
    inclinationDeg: 7.0,
    eccentricity: 0.2056,
    rotationDays: 58.646,
    blurb: "Smallest planet — scorched dayside, frozen night, eccentric orbit. No moons.",
    stats: {
      "Semi-major": "0.387 AU",
      Year: "88 d",
      Day: "59 d",
      Moons: "0",
    },
  },
  {
    id: "venus",
    name: "Venus",
    type: "Terrestrial",
    color: 0xe8c87a,
    radiusKm: 6051.8,
    visualRadius: 0.48,
    a_au: 0.723,
    periodDays: 224.701,
    inclinationDeg: 3.4,
    eccentricity: 0.0067,
    rotationDays: -243.025,
    blurb: "Earth’s twin by size — runaway greenhouse, retrograde spin. No moons.",
    stats: {
      "Semi-major": "0.723 AU",
      Year: "225 d",
      Day: "−243 d",
      Moons: "0",
    },
  },
  {
    id: "earth",
    name: "Earth",
    type: "Terrestrial",
    color: 0x3b82f6,
    atmosphere: 0x60a5fa,
    radiusKm: 6371,
    visualRadius: 0.52,
    a_au: 1.0,
    periodDays: 365.256,
    inclinationDeg: 0.0,
    eccentricity: 0.0167,
    rotationDays: 0.997,
    blurb: "The pale blue dot — liquid water, life, and Luna. Press E for Earth LEO theater.",
    stats: {
      "Semi-major": "1.000 AU",
      Year: "365.26 d",
      Day: "23.93 h",
      Moons: moonCountLabel(EARTH_MOONS),
      LEO: "Press E",
    },
    moons: EARTH_MOONS,
  },
  {
    id: "mars",
    name: "Mars",
    type: "Terrestrial",
    color: 0xe07a5f,
    radiusKm: 3389.5,
    visualRadius: 0.36,
    a_au: 1.524,
    periodDays: 686.98,
    inclinationDeg: 1.85,
    eccentricity: 0.0934,
    rotationDays: 1.026,
    blurb: "The red planet — thin CO₂ air, polar caps, and two potato moons: Phobos & Deimos.",
    stats: {
      "Semi-major": "1.524 AU",
      Year: "687 d",
      Day: "24.6 h",
      Moons: moonCountLabel(MARS_MOONS),
    },
    moons: MARS_MOONS,
  },
  {
    id: "jupiter",
    name: "Jupiter",
    type: "Gas giant",
    color: 0xd4a574,
    radiusKm: 69911,
    visualRadius: 1.35,
    a_au: 5.203,
    periodDays: 4332.59,
    inclinationDeg: 1.3,
    eccentricity: 0.0489,
    rotationDays: 0.414,
    hasCrown: true,
    blurb:
      "King of planets — wears the crown. Galilean moons plus a vast swarm of smaller satellites attend court.",
    stats: {
      "Semi-major": "5.20 AU",
      Year: "11.86 y",
      Day: "9.9 h",
      Moons: moonCountLabel(JUPITER_MOONS),
      Status: "Giant · crowned",
    },
    moons: JUPITER_MOONS,
  },
  {
    id: "saturn",
    name: "Saturn",
    type: "Gas giant",
    color: 0xe6d5a8,
    radiusKm: 58232,
    visualRadius: 1.15,
    a_au: 9.537,
    periodDays: 10759.22,
    inclinationDeg: 2.49,
    eccentricity: 0.0565,
    rotationDays: 0.444,
    hasRings: true,
    blurb: "Ringed jewel — Titan, Enceladus, and the most moons in the solar system.",
    stats: {
      "Semi-major": "9.54 AU",
      Year: "29.46 y",
      Day: "10.7 h",
      Moons: moonCountLabel(SATURN_MOONS),
    },
    moons: SATURN_MOONS,
  },
  {
    id: "uranus",
    name: "Uranus",
    type: "Ice giant",
    color: 0x7dd3c7,
    radiusKm: 25362,
    visualRadius: 0.78,
    a_au: 19.191,
    periodDays: 30688.5,
    inclinationDeg: 0.77,
    eccentricity: 0.0457,
    rotationDays: -0.718,
    blurb: "Sideways ice giant — Shakespearean moons (Titania, Oberon, Miranda…).",
    stats: {
      "Semi-major": "19.2 AU",
      Year: "84.0 y",
      Day: "−17.2 h",
      Moons: moonCountLabel(URANUS_MOONS),
    },
    moons: URANUS_MOONS,
  },
  {
    id: "neptune",
    name: "Neptune",
    type: "Ice giant",
    color: 0x4169e1,
    radiusKm: 24622,
    visualRadius: 0.75,
    a_au: 30.069,
    periodDays: 60182,
    inclinationDeg: 1.77,
    eccentricity: 0.0113,
    rotationDays: 0.671,
    blurb: "Farthest giant — retrograde Triton rules a cold court of moons.",
    stats: {
      "Semi-major": "30.1 AU",
      Year: "164.8 y",
      Day: "16.1 h",
      Moons: moonCountLabel(NEPTUNE_MOONS),
    },
    moons: NEPTUNE_MOONS,
  },
  {
    id: "pluto",
    name: "Pluto",
    type: "Dwarf planet",
    color: 0xc4a882,
    radiusKm: 1188,
    visualRadius: 0.32,
    a_au: 39.482,
    periodDays: 90560,
    inclinationDeg: 17.16,
    eccentricity: 0.2488,
    rotationDays: -6.387,
    hasCrown: true,
    blurb:
      "King of the Kuiper belt (in our hearts). Still wears the crown — Charon and the small moons attend court.",
    stats: {
      "Semi-major": "39.5 AU",
      Year: "248 y",
      Day: "−6.4 d",
      Moons: moonCountLabel(PLUTO_MOONS),
      Status: "Dwarf · crowned",
    },
    moons: PLUTO_MOONS,
  },
];

/**
 * Periodic comets — high eccentricity, long tails near perihelion.
 * Elements are simplified educational approximations (not JPL SPK-grade).
 */
export const COMETS = [
  {
    id: "halley",
    name: "1P/Halley",
    type: "Comet",
    color: 0xb8d4ff,
    tailDust: 0xffe4b5,
    tailIon: 0x7dd3fc,
    visualRadius: 0.14,
    a_au: 17.834,
    periodDays: 75.32 * 365.256,
    inclinationDeg: 162.3,
    eccentricity: 0.967,
    phase0: 0.35,
    blurb: "The famous Halley — retrograde, ~76-year period, spectacular near perihelion.",
    stats: {
      "Semi-major": "17.8 AU",
      Year: "75.3 y",
      e: "0.967",
      Incl: "162°",
    },
  },
  {
    id: "encke",
    name: "2P/Encke",
    type: "Comet",
    color: 0xd4e4f7,
    tailDust: 0xf5d0a9,
    tailIon: 0x93c5fd,
    visualRadius: 0.11,
    a_au: 2.21,
    periodDays: 3.3 * 365.256,
    inclinationDeg: 11.8,
    eccentricity: 0.848,
    phase0: 1.1,
    blurb: "Short-period workhorse — one of the shortest known cometary periods (~3.3 y).",
    stats: {
      "Semi-major": "2.21 AU",
      Year: "3.3 y",
      e: "0.848",
      Incl: "12°",
    },
  },
  {
    id: "hale-bopp",
    name: "C/1995 O1 Hale–Bopp",
    type: "Comet",
    color: 0xc4e0ff,
    tailDust: 0xffecc8,
    tailIon: 0x67e8f9,
    visualRadius: 0.16,
    a_au: 186,
    periodDays: 2533 * 365.256,
    inclinationDeg: 89.4,
    eccentricity: 0.9951,
    phase0: 4.2,
    blurb: "Great Comet of 1997 — huge nucleus, dual dust + ion tails, millennia-class orbit.",
    stats: {
      "Semi-major": "~186 AU",
      Year: "~2,500 y",
      e: "0.995",
      Incl: "89°",
    },
  },
  {
    id: "swift-tuttle",
    name: "109P/Swift–Tuttle",
    type: "Comet",
    color: 0xaed4ff,
    tailDust: 0xffd9a0,
    tailIon: 0x38bdf8,
    visualRadius: 0.13,
    a_au: 26.092,
    periodDays: 133.28 * 365.256,
    inclinationDeg: 113.45,
    eccentricity: 0.9632,
    phase0: 2.4,
    blurb: "Parent of the Perseids — large nucleus, retrograde-ish long period.",
    stats: {
      "Semi-major": "26.1 AU",
      Year: "133 y",
      e: "0.963",
      Incl: "113°",
    },
  },
  {
    id: "tempel1",
    name: "9P/Tempel 1",
    type: "Comet",
    color: 0xc8d8e8,
    tailDust: 0xe8d4b8,
    tailIon: 0x7dd3fc,
    visualRadius: 0.1,
    a_au: 3.145,
    periodDays: 5.58 * 365.256,
    inclinationDeg: 10.5,
    eccentricity: 0.51,
    phase0: 0.8,
    blurb: "Deep Impact target (2005) — Jupiter-family comet with a moderate eccentricity.",
    stats: {
      "Semi-major": "3.15 AU",
      Year: "5.6 y",
      e: "0.51",
      Incl: "10°",
    },
  },
];
