/**
 * Episode 11 — The Chakravyuha
 * Drona Parva · thirteenth day; Abhimanyu; the wheel of war
 */
export const EPISODE = {
  id: "11",
  slug: "chakravyuha",
  title: "The Chakravyuha",
  subtitle: "Thirteenth day of Kurukshetra",
  style: "cinematic-plates",
  stillsDir: "episodes/11-chakravyuha/stills/",
  voice: {
    provider: "grok-tts",
    voice_id: "orion",
    cache: "ep11-gold-restyle",
    note: "Kathavachak — orion when available; ep11-v1 is macOS Aman fallback",
    base: "episodes/11-chakravyuha/audio/",
  },
  music: {
    raga: "megh",
    note: "Megh + circling Jhaptal (the vyuha); reed color. Duck under Orion.",
  },
  totalSec: 104,
  stills: {
    poster: "episodes/11-chakravyuha/stills/poster.jpg",
  },
  plates: {
    wide: "plate-wide.jpg",
    vyuha: "plate-vyuha.jpg",
    counsel: "plate-counsel.jpg",
    enter: "plate-enter.jpg",
    gate: "plate-gate.jpg",
    storm: "plate-storm.jpg",
    wheel: "plate-wheel.jpg",
    dusk: "plate-dusk.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  end: {
    title: "End of Episode 11",
    line: "The wheel is closed. Tomorrow the Sindhu king must fall, or the sun will not rise for Arjuna.",
    next: "index.html",
    nextLabel: "All episodes",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    silver: "#c5d0dc",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      audio: "orion-00.mp3",
      who: "Narrator",
      text: "The grandsire has fallen. Drona takes the Kaurava host — and the field learns a new commander.",
    },
    {
      t: 12,
      plate: "vyuha",
      zoom: 1.12,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-01.mp3",
      who: "Narrator",
      text: "He arrays a wheel of war, the Chakravyuha — rings of chariots turning like a living mandala.",
    },
    {
      t: 24,
      plate: "counsel",
      zoom: 1.14,
      panX: -0.02,
      panY: -0.02,
      audio: "orion-02.mp3",
      who: "Narrator",
      text: "Arjuna is drawn to the far flank. Abhimanyu stands forth: I know the way in — not the way out.",
    },
    {
      t: 36,
      plate: "enter",
      zoom: 1.14,
      panX: 0.03,
      panY: -0.02,
      audio: "orion-03.mp3",
      who: "Narrator",
      text: "The son of Arjuna drives into the spinning rings, and the wheel closes behind him.",
    },
    {
      t: 48,
      plate: "gate",
      zoom: 1.16,
      panX: 0,
      panY: -0.03,
      audio: "orion-04.mp3",
      who: "Narrator",
      text: "At the rim Jayadratha holds the four brothers — a living gate they cannot pass.",
    },
    {
      t: 60,
      plate: "storm",
      zoom: 1.14,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-05.mp3",
      who: "Narrator",
      text: "Inside, the young lion fights as his father fights — a storm of gold shafts, and no one stands near him.",
    },
    {
      t: 72,
      plate: "wheel",
      zoom: 1.18,
      panX: 0,
      panY: 0.02,
      audio: "orion-06.mp3",
      who: "Narrator",
      text: "His bow is broken. He lifts a chariot wheel — last weapon of a kshatriya.",
    },
    {
      t: 84,
      plate: "dusk",
      zoom: 1.12,
      panX: -0.02,
      panY: -0.02,
      audio: "orion-07.mp3",
      who: "Narrator",
      text: "He falls as a young tree falls — and the thirteenth day darkens.",
    },
    {
      t: 95,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      audio: "orion-08.mp3",
      who: "Narrator",
      text: "Arjuna returns at dusk. He vows: tomorrow Jayadratha dies, or I do not see the sun.",
    },
    {
      t: 102,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
