/**
 * Episode 08 — The Peace Embassy
 * Udyoga Parva · Krishna goes to Hastinapura
 */
export const EPISODE = {
  id: "08",
  slug: "peace-embassy",
  title: "The Peace Embassy",
  subtitle: "Krishna at Hastinapura",
  style: "cinematic-plates",
  stillsDir: "episodes/08-peace-embassy/stills/",
  voice: {
    provider: "grok-tts",
    voice_id: "orion",
    cache: "ep08-v1",
    note: "Grok TTS orion — deep heroic narration",
    base: "episodes/08-peace-embassy/audio/",
  },
  totalSec: 102,
  stills: {
    poster: "episodes/08-peace-embassy/stills/poster.jpg",
  },
  plates: {
    wide: "plate-wide.jpg",
    mission: "plate-mission.jpg",
    journey: "plate-journey.jpg",
    court: "plate-court.jpg",
    offer: "plate-offer.jpg",
    refuse: "plate-refuse.jpg",
    form: "plate-form.jpg",
    war: "plate-war.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  end: {
    title: "End of Episode 08",
    line: "When peace is refused, dharma takes the field.",
    next: "play.html?ep=09",
    nextLabel: "Play Episode 09",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      audio: "orion-00.mp3",
      who: "Narrator",
      text: "The years of exile end. Armies gather — and one last chance for peace remains.",
    },
    {
      t: 10,
      plate: "mission",
      zoom: 1.12,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-01.mp3",
      who: "Narrator",
      text: "Krishna takes the Pandavas’ plea to Hastinapura: five villages, and no war.",
    },
    {
      t: 22,
      plate: "journey",
      zoom: 1.1,
      panX: -0.03,
      panY: 0,
      audio: "orion-02.mp3",
      who: "Narrator",
      text: "He rides toward the city of the Kurus as messenger, friend, and witness of dharma.",
    },
    {
      t: 34,
      plate: "court",
      zoom: 1.14,
      panX: 0.03,
      panY: -0.03,
      audio: "orion-03.mp3",
      who: "Narrator",
      text: "In the great sabha Dhritarashtra sits blind; Duryodhana’s pride fills the hall.",
    },
    {
      t: 46,
      plate: "offer",
      zoom: 1.16,
      panX: 0,
      panY: -0.02,
      audio: "orion-04.mp3",
      who: "Narrator",
      text: "Krishna offers peace: five villages for the sons of Pandu. Nothing more is asked.",
    },
    {
      t: 58,
      plate: "refuse",
      zoom: 1.14,
      panX: 0.04,
      panY: -0.02,
      audio: "orion-05.mp3",
      who: "Narrator",
      text: "Duryodhana refuses. He will not give land enough to drive a needle’s point.",
    },
    {
      t: 70,
      plate: "form",
      zoom: 1.2,
      panX: 0.02,
      panY: -0.04,
      audio: "orion-06.mp3",
      who: "Narrator",
      text: "When they plot to seize him, Krishna shows a fraction of his cosmic form — and the hall trembles.",
    },
    {
      t: 82,
      plate: "war",
      zoom: 1.12,
      panX: -0.02,
      panY: 0,
      audio: "orion-07.mp3",
      who: "Narrator",
      text: "He returns to the Pandavas. Peace has failed. The road to Kurukshetra is open.",
    },
    {
      t: 92,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      audio: "orion-08.mp3",
      who: "Narrator",
      text: "Thus the last word of peace was spoken — and the age turned toward battle.",
    },
    {
      t: 100,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
