/**
 * Episode 08 — The Peace Embassy
 * Udyoga Parva · Krishna’s embassy to Hastinapura · five villages · refusal · form
 * Rewrite: Ep 09/10 bar; SuperGrok stills GATE C PASS (2026-09-18).
 *
 * Audio: orion-00…08 re-rendered 2026-10-04 with free local Kokoro-82M bm_george
 * (tools/render_local_voice.sh, speed 0.9); PRONOUNCE for Hastinapura/Dhritarashtra/Duryodhana/Pandu/Kurus/sabha/dharma.
 * Beat t retimed from ffprobe (12 s grid; clip ends ≥1 s before next beat).
 * Music: named Hindustani raga Yaman (never default flute+tabla).
 */
export const EPISODE = {
  id: "08",
  slug: "peace-embassy",
  title: "The Peace Embassy",
  subtitle: "Krishna at Hastinapura",
  style: "cinematic-plates",
  stillsDir: "episodes/08-peace-embassy/stills/",
  voice: {
    provider: "local-kokoro",
    voice_id: "bm_george",
    cache: "ep08-kokoro-20261004",
    note: "Kathavachak — Kokoro-82M bm_george (free local, Apache-2.0, speed 0.9) via tools/render_local_voice.sh; no paid xAI API (SuperGrok-only rule). Files keep orion-NN.mp3 names/fingerprint (24 kHz / 128 kbps / mono / -16 LUFS).",
    base: "episodes/08-peace-embassy/audio/",
  },
  music: {
    raga: "yaman",
    note: "Yaman mandra tanpura; sparse bansuri; no tabla. Evening peace embassy / sabha resolve. Duck under Orion. Not default flute+tabla.",
  },
  totalSec: 110,
  stills: {
    poster: "episodes/08-peace-embassy/stills/poster.jpg",
  },
  plates: {
    wide: "plate-wide.jpg",
    mission: "plate-mission.jpg",
    journey: "plate-journey.jpg",
    court: "plate-court.jpg",
    offer: "plate-offer.jpg",
    refuse: "plate-refuse.jpg",
    form: "plate-form.jpg",
    war: "plate-war.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  end: {
    title: "End of Episode 08",
    line: "When peace is refused, dharma takes the field.",
    next: "play.html?ep=09",
    nextLabel: "Play Episode 09",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      audio: "orion-00.mp3",
      who: "Narrator",
      text: "The years of exile end. Armies gather — and one last chance for peace remains.",
    },
    {
      t: 12,
      plate: "mission",
      zoom: 1.12,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-01.mp3",
      who: "Narrator",
      text: "Krishna takes the Pandavas’ plea to Hastinapura: five villages, and no war.",
    },
    {
      t: 24,
      plate: "journey",
      zoom: 1.1,
      panX: -0.03,
      panY: 0,
      audio: "orion-02.mp3",
      who: "Narrator",
      text: "He rides toward the city of the Kurus as messenger, friend, and witness of dharma.",
    },
    {
      t: 36,
      plate: "court",
      zoom: 1.14,
      panX: 0.03,
      panY: -0.03,
      audio: "orion-03.mp3",
      who: "Narrator",
      text: "In the great sabha Dhritarashtra sits blind; Duryodhana’s pride fills the hall.",
    },
    {
      t: 48,
      plate: "offer",
      zoom: 1.16,
      panX: 0,
      panY: -0.02,
      audio: "orion-04.mp3",
      who: "Narrator",
      text: "Krishna offers peace: five villages for the sons of Pandu. Nothing more is asked.",
    },
    {
      t: 60,
      plate: "refuse",
      zoom: 1.14,
      panX: 0.04,
      panY: -0.02,
      audio: "orion-05.mp3",
      who: "Narrator",
      text: "Duryodhana refuses. He will not give land enough to drive a needle’s point.",
    },
    {
      t: 72,
      plate: "form",
      zoom: 1.2,
      panX: 0.02,
      panY: -0.04,
      audio: "orion-06.mp3",
      who: "Narrator",
      text: "When they plot to seize him, Krishna shows a fraction of his cosmic form — and the hall trembles.",
    },
    {
      t: 84,
      plate: "war",
      zoom: 1.12,
      panX: -0.02,
      panY: 0,
      audio: "orion-07.mp3",
      who: "Narrator",
      text: "He returns to the Pandavas. Peace has failed. The road to Kurukshetra is open.",
    },
    {
      t: 96,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      audio: "orion-08.mp3",
      who: "Narrator",
      text: "Thus the last word of peace was spoken — and the age turned toward battle.",
    },
    {
      t: 108,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
