/**
 * Episode 04 — Durvasa and the Akshayapatra
 * Vana Parva · the inexhaustible vessel · cinematic plates + Orion TTS + flute/tabla.
 */
export const EPISODE = {
  id: "04",
  slug: "akshayapatra",
  title: "The Akshayapatra",
  subtitle: "Durvasa and the grain of grace",
  style: "cinematic-plates",
  stillsDir: "episodes/04-akshayapatra/stills/",
  voice: {
    provider: "grok-tts",
    voice_id: "orion",
    cache: "ep04-v1",
    note: "Grok TTS orion — deep heroic narration",
    base: "episodes/04-akshayapatra/audio/",
  },
  totalSec: 100,
  stills: {
    poster: "episodes/04-akshayapatra/stills/poster.jpg",
  },
  plates: {
    wide: "plate-wide.jpg",
    vessel: "plate-vessel.jpg",
    empty: "plate-empty.jpg",
    arrival: "plate-arrival.jpg",
    prayer: "plate-prayer.jpg",
    krishna: "plate-krishna.jpg",
    grain: "plate-grain.jpg",
    satisfied: "plate-satisfied.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  end: {
    title: "End of Episode 04",
    line: "When the heart is true, even a grain can feed the world.",
    next: "index.html",
    nextLabel: "All episodes",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      audio: "orion-00.mp3",
      who: "Narrator",
      text: "In the forest of exile the Pandavas keep a simple camp — and one divine gift that never runs dry by day.",
    },
    {
      t: 10,
      plate: "vessel",
      zoom: 1.14,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-01.mp3",
      who: "Narrator",
      text: "The Akshayapatra: so long as Draupadi has not finished her meal, the vessel feeds every guest.",
    },
    {
      t: 22,
      plate: "empty",
      zoom: 1.12,
      panX: -0.02,
      panY: 0,
      audio: "orion-02.mp3",
      who: "Narrator",
      text: "One evening the meal is done. Draupadi washes the vessel clean — and the day’s grace is sealed.",
    },
    {
      t: 32,
      plate: "arrival",
      zoom: 1.1,
      panX: 0.04,
      panY: -0.02,
      audio: "orion-03.mp3",
      who: "Narrator",
      text: "Then comes sage Durvasa with a throng of hungry disciples — and the camp has nothing left to offer.",
    },
    {
      t: 44,
      plate: "prayer",
      zoom: 1.16,
      panX: 0,
      panY: -0.03,
      audio: "orion-04.mp3",
      who: "Narrator",
      text: "Draupadi’s heart trembles. She prays to Krishna, the friend who never abandons the devoted.",
    },
    {
      t: 54,
      plate: "krishna",
      zoom: 1.12,
      panX: 0.03,
      panY: 0,
      audio: "orion-05.mp3",
      who: "Narrator",
      text: "Krishna arrives, smiling as if the forest itself has exhaled.",
    },
    {
      t: 64,
      plate: "grain",
      zoom: 1.22,
      panX: 0.02,
      panY: -0.04,
      audio: "orion-06.mp3",
      who: "Narrator",
      text: "He finds a single grain of rice clinging to the vessel — and eats it with love.",
    },
    {
      t: 76,
      plate: "satisfied",
      zoom: 1.12,
      panX: -0.02,
      panY: 0,
      audio: "orion-07.mp3",
      who: "Narrator",
      text: "Far away, Durvasa and his disciples feel full. They bless the Pandavas and turn back, content.",
    },
    {
      t: 88,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      audio: "orion-08.mp3",
      who: "Narrator",
      text: "So grace filled what fear had emptied — and the forest remembered Krishna’s name.",
    },
    {
      t: 98,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
