/**
 * Episode 04 — The Akshayapatra
 * Vana (Āraṇyaka) Parva · Sūrya's vessel; Durvāsā-upākhyāna (Draupadīharaṇa-parva)
 * Logic pass 2026-10-01 (Ep 14 standard): exile hermitage feeds every guest → Sūrya's vessel and its rule
 * (inexhaustible until Draupadi eats) → Duryodhana's boon: Durvasa to visit after she has eaten →
 * vessel spent → Durvasa + ten thousand arrive, go to bathe → Draupadi prays → Krishna, hungry, asks for the
 * vessel → eats the particle on the rim → sages sated in the river flee → Bhima finds the bank empty; trap closes on nothing.
 * Sources: BORI CE/Debroy Āraṇyaka 3.3 + Gita Press Gorakhpur Vana 3, 262–263 + K.M. Ganguli Vana III, CCLX–CCLXI.
 * Durvāsā episode is vulgate-only (not in BORI CE constituted text). See plate-bible source_block.
 * Audio: orion-00…09 re-rendered 2026-10-02 with free local Kokoro-82M bm_george (tools/render_local_voice.sh, speed 0.9);
 * beat t retimed from ffprobe (12 s grid, clip ends ≥1 s before next beat; overruns extend the slot).
 * Plates: boon (new) + satisfied (river) imported from SuperGrok consumer Imagine 2026-10-02 — GATE C PASS (RR-gateC-visual.md).
 */
export const EPISODE = {
  id: "04",
  slug: "akshayapatra",
  title: "The Akshayapatra",
  subtitle: "Durvasa and the grain of grace",
  style: "cinematic-plates",
  stillsDir: "episodes/04-akshayapatra/stills/",
  voice: {
    provider: "local-kokoro",
    voice_id: "bm_george",
    cache: "ep04-local-20261002",
    note: "Kathavachak — Kokoro-82M bm_george (free local, Apache-2.0, speed 0.9) via tools/render_local_voice.sh; no paid xAI API (SuperGrok-only rule). Files keep orion-NN.mp3 names/fingerprint (24 kHz / 128 kbps / mono / -16 LUFS).",
    base: "episodes/04-akshayapatra/audio/",
  },
  music: {
    raga: "yaman",
    note: "Yaman (evening Kalyan, tivra Ma) — devotional trust; tanpura + sparse bansuri, no tabla. Duck under narration. Replaces default flute+tabla.",
  },
  totalSec: 130,
  stills: {
    poster: "episodes/04-akshayapatra/stills/poster.jpg",
  },
  plates: {
    wide: "plate-wide.jpg",
    vessel: "plate-vessel.jpg",
    boon: "plate-boon.jpg",
    empty: "plate-empty.jpg",
    arrival: "plate-arrival.jpg",
    prayer: "plate-prayer.jpg",
    krishna: "plate-krishna.jpg",
    grain: "plate-grain.jpg",
    satisfied: "plate-satisfied.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  end: {
    title: "End of Episode 04",
    line: "When the heart is true, even a grain can feed the world.",
    next: "play.html?ep=05",
    nextLabel: "Play Episode 05",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      audio: "orion-00.mp3",
      who: "Narrator",
      text: "Twelve years of forest exile. The Pandavas live in a simple hermitage — yet every sage who comes to them is fed, and many come.",
    },
    {
      t: 12,
      plate: "vessel",
      zoom: 1.14,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-01.mp3",
      who: "Narrator",
      text: "The Sun god gave Yudhishthira this vessel, the Akshayapatra. Whatever Draupadi cooks in it never runs out — until she, last of all, has eaten.",
    },
    {
      t: 24,
      plate: "boon",
      zoom: 1.1,
      panX: -0.02,
      panY: -0.02,
      audio: "orion-02.mp3",
      who: "Narrator",
      text: "In Hastinapura, Duryodhana cannot bear their peace. He serves the short-tempered sage Durvasa until the sage offers a boon — then asks him to visit his cousins after Draupadi has eaten.",
    },
    {
      t: 40,
      plate: "empty",
      zoom: 1.12,
      panX: -0.02,
      panY: 0,
      audio: "orion-03.mp3",
      who: "Narrator",
      text: "So the sage comes late. Draupadi has fed everyone, eaten last, and set the vessel aside, scoured clean. Today’s food is gone.",
    },
    {
      t: 52,
      plate: "arrival",
      zoom: 1.1,
      panX: 0.04,
      panY: -0.02,
      audio: "orion-04.mp3",
      who: "Narrator",
      text: "Then Durvasa arrives with ten thousand disciples. Yudhishthira welcomes them, and they go to bathe in the river, expecting a feast on their return.",
    },
    {
      t: 65,
      plate: "prayer",
      zoom: 1.16,
      panX: 0,
      panY: -0.03,
      audio: "orion-05.mp3",
      who: "Narrator",
      text: "There is nothing left to cook, and Durvasa’s curse is feared across the worlds. Draupadi turns to her one refuge — she prays to Krishna.",
    },
    {
      t: 77,
      plate: "krishna",
      zoom: 1.12,
      panX: 0.03,
      panY: 0,
      audio: "orion-06.mp3",
      who: "Narrator",
      text: "Krishna comes at once — and before she can speak, he says he is hungry. “The vessel is empty,” Draupadi cries. “Bring it anyway,” he smiles.",
    },
    {
      t: 89,
      plate: "grain",
      zoom: 1.22,
      panX: 0.02,
      panY: -0.04,
      audio: "orion-07.mp3",
      who: "Narrator",
      text: "On the rim he finds one grain of rice and a shred of leaf. He eats it: “May the Soul of the universe be satisfied.”",
    },
    {
      t: 101,
      plate: "satisfied",
      zoom: 1.12,
      panX: -0.02,
      panY: 0,
      audio: "orion-08.mp3",
      who: "Narrator",
      text: "In the river, Durvasa and his disciples suddenly feel full. Unable to eat the feast they asked for, and afraid of the Pandavas’ anger, they slip away.",
    },
    {
      t: 114,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      audio: "orion-09.mp3",
      who: "Narrator",
      text: "Bhima runs to call them to dinner, but the riverbank is empty. Duryodhana’s trap has closed on nothing — and Krishna smiles and takes his leave.",
    },
    {
      t: 126,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
