/**
 * Episode 07 — Jayadratha
 * Vana Parva · Draupadi’s abduction · the Pandavas’ pursuit
 */
export const EPISODE = {
  id: "07",
  slug: "jayadratha",
  title: "Jayadratha",
  subtitle: "The abduction in the forest",
  style: "cinematic-plates",
  stillsDir: "episodes/07-jayadratha/stills/",
  voice: {
    provider: "grok-tts",
    voice_id: "orion",
    cache: "ep07-v1",
    note: "Grok TTS orion — deep heroic narration",
    base: "episodes/07-jayadratha/audio/",
  },
  totalSec: 100,
  stills: {
    poster: "episodes/07-jayadratha/stills/poster.jpg",
  },
  plates: {
    wide: "plate-wide.jpg",
    alone: "plate-alone.jpg",
    approach: "plate-approach.jpg",
    seize: "plate-seize.jpg",
    cry: "plate-cry.jpg",
    chase: "plate-chase.jpg",
    catch: "plate-catch.jpg",
    mercy: "plate-mercy.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  end: {
    title: "End of Episode 07",
    line: "Honor defended is not always honor unbroken — the forest remembers every insult.",
    next: "play.html?ep=08",
    nextLabel: "Play Episode 08",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      audio: "orion-00.mp3",
      who: "Narrator",
      text: "While the Pandavas hunt, Draupadi keeps the forest hermitage alone.",
    },
    {
      t: 10,
      plate: "alone",
      zoom: 1.12,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-01.mp3",
      who: "Narrator",
      text: "Jayadratha, king of Sindhu, rides past and sees her — and desire turns to crime.",
    },
    {
      t: 20,
      plate: "approach",
      zoom: 1.1,
      panX: -0.03,
      panY: 0,
      audio: "orion-02.mp3",
      who: "Narrator",
      text: "He greets her with soft words. She answers with the dignity of a queen in exile.",
    },
    {
      t: 32,
      plate: "seize",
      zoom: 1.16,
      panX: 0.03,
      panY: -0.03,
      audio: "orion-03.mp3",
      who: "Narrator",
      text: "When soft words fail, his men seize her chariot and carry Draupadi away.",
    },
    {
      t: 42,
      plate: "cry",
      zoom: 1.14,
      panX: 0,
      panY: -0.02,
      audio: "orion-04.mp3",
      who: "Narrator",
      text: "Her cry reaches the forest. The brothers hear it and turn from the hunt.",
    },
    {
      t: 52,
      plate: "chase",
      zoom: 1.18,
      panX: 0.04,
      panY: -0.04,
      audio: "orion-05.mp3",
      who: "Narrator",
      text: "Arjuna and Bhima lead the chase — dust and arrows on the forest road.",
    },
    {
      t: 64,
      plate: "catch",
      zoom: 1.16,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-06.mp3",
      who: "Narrator",
      text: "They overtake Jayadratha. Bhima would end him; Draupadi’s honor is restored.",
    },
    {
      t: 76,
      plate: "mercy",
      zoom: 1.12,
      panX: -0.02,
      panY: 0,
      audio: "orion-07.mp3",
      who: "Narrator",
      text: "Yudhishthira grants a hard mercy — Jayadratha lives, shamed, and rides home.",
    },
    {
      t: 88,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      audio: "orion-08.mp3",
      who: "Narrator",
      text: "The forest is quiet again — but every insult of exile will be paid in war.",
    },
    {
      t: 98,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
