/**
 * Episode 07 — Jayadratha
 * Vana Parva · Draupadi’s abduction · the Pandavas’ pursuit · hard mercy
 * Rewrite: Ep 09/10 bar; SuperGrok stills GATE C PASS (2026-09-17).
 *
 * Audio: orion-00…08 re-rendered 2026-10-04 with free local Kokoro-82M bm_george
 * (tools/render_local_voice.sh, speed 0.9); PRONOUNCE for Jayadratha/Draupadi/Sindhu/Bhima/Yudhishthira/Arjuna/Pandavas.
 * Beat t retimed from ffprobe (12 s grid; clip ends ≥1 s before next beat).
 * Music: named Hindustani raga Bhairavi (never default flute+tabla).
 */
export const EPISODE = {
  id: "07",
  slug: "jayadratha",
  title: "Jayadratha",
  subtitle: "The abduction in the forest",
  style: "cinematic-plates",
  stillsDir: "episodes/07-jayadratha/stills/",
  voice: {
    provider: "local-kokoro",
    voice_id: "bm_george",
    cache: "ep07-kokoro-20261004",
    note: "Kathavachak — Kokoro-82M bm_george (free local, Apache-2.0, speed 0.9) via tools/render_local_voice.sh; no paid xAI API (SuperGrok-only rule). Files keep orion-NN.mp3 names/fingerprint (24 kHz / 128 kbps / mono / -16 LUFS).",
    base: "episodes/07-jayadratha/audio/",
  },
  music: {
    raga: "bhairavi",
    note: "Bhairavi mandra tanpura; sparse bansuri; no tabla. Draupadi dignity / forest ordeal / hard mercy. Duck under Orion. Not default flute+tabla.",
  },
  totalSec: 110,
  stills: {
    poster: "episodes/07-jayadratha/stills/poster.jpg",
  },
  plates: {
    wide: "plate-wide.jpg",
    alone: "plate-alone.jpg",
    approach: "plate-approach.jpg",
    seize: "plate-seize.jpg",
    cry: "plate-cry.jpg",
    chase: "plate-chase.jpg",
    catch: "plate-catch.jpg",
    mercy: "plate-mercy.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  end: {
    title: "End of Episode 07",
    line: "Honor defended is not always honor unbroken — the forest remembers every insult.",
    next: "play.html?ep=08",
    nextLabel: "Play Episode 08",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      audio: "orion-00.mp3",
      who: "Narrator",
      text: "While the Pandavas hunt, Draupadi keeps the forest hermitage alone.",
    },
    {
      t: 12,
      plate: "alone",
      zoom: 1.12,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-01.mp3",
      who: "Narrator",
      text: "Jayadratha, king of Sindhu, rides past and sees her — and desire turns to crime.",
    },
    {
      t: 24,
      plate: "approach",
      zoom: 1.1,
      panX: -0.03,
      panY: 0,
      audio: "orion-02.mp3",
      who: "Narrator",
      text: "He greets her with soft words. She answers with the dignity of a queen in exile.",
    },
    {
      t: 36,
      plate: "seize",
      zoom: 1.16,
      panX: 0.03,
      panY: -0.03,
      audio: "orion-03.mp3",
      who: "Narrator",
      text: "When soft words fail, his men seize her and drive the chariot away.",
    },
    {
      t: 48,
      plate: "cry",
      zoom: 1.14,
      panX: 0,
      panY: -0.02,
      audio: "orion-04.mp3",
      who: "Narrator",
      text: "Her cry reaches the forest. The brothers hear it and turn from the hunt.",
    },
    {
      t: 60,
      plate: "chase",
      zoom: 1.18,
      panX: 0.04,
      panY: -0.04,
      audio: "orion-05.mp3",
      who: "Narrator",
      text: "Arjuna and Bhima lead the chase — dust and arrows on the forest road.",
    },
    {
      t: 72,
      plate: "catch",
      zoom: 1.16,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-06.mp3",
      who: "Narrator",
      text: "They overtake Jayadratha. Bhima would end him; Draupadi stands free.",
    },
    {
      t: 84,
      plate: "mercy",
      zoom: 1.12,
      panX: -0.02,
      panY: 0,
      audio: "orion-07.mp3",
      who: "Narrator",
      text: "Yudhishthira grants a hard mercy — Jayadratha lives, shamed, and rides home.",
    },
    {
      t: 96,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      audio: "orion-08.mp3",
      who: "Narrator",
      text: "The forest is quiet again — but every insult of exile will be paid in war.",
    },
    {
      t: 108,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
