/**
 * Episode 14 — The Fall of Drona
 * Drona Parva · fifteenth day; the elephant; the guru sits
 */
export const EPISODE = {
  id: "14",
  slug: "drona-fall",
  title: "The Fall of Drona",
  subtitle: "Fifteenth day of Kurukshetra",
  style: "cinematic-plates",
  stillsDir: "episodes/14-drona-fall/stills/",
  voice: {
    provider: "grok-tts",
    voice_id: "orion",
    cache: "ep14-orion",
    note: "Kathavachak — grok-tts Orion (same pipeline as Ep 09–13)",
    base: "episodes/14-drona-fall/audio/",
  },
  music: {
    raga: "todi",
    note: "Morning Todi tanpura + sparse bansuri; pathos, no tabla. Duck under Orion.",
  },
  totalSec: 104,
  stills: {
    poster: "episodes/14-drona-fall/stills/poster.jpg",
  },
  plates: {
    wide: "plate-wide.jpg",
    counsel: "plate-counsel.jpg",
    elephant: "plate-elephant.jpg",
    dharma: "plate-dharma.jpg",
    conch: "plate-conch.jpg",
    yoga: "plate-yoga.jpg",
    prince: "plate-prince.jpg",
    still: "plate-still.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  end: {
    title: "End of Episode 14",
    line: "The guru is still. A son not on this field will hear it.",
    next: "index.html",
    nextLabel: "All episodes",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      audio: "orion-00.mp3",
      who: "Narrator",
      text: "Dawn of the fifteenth. Drona holds the field like a second sun.",
    },
    {
      t: 12,
      plate: "counsel",
      zoom: 1.14,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-01.mp3",
      who: "Narrator",
      text: "Krishna says: he will not fall while he believes his son lives.",
    },
    {
      t: 24,
      plate: "elephant",
      zoom: 1.12,
      panX: -0.02,
      panY: -0.02,
      audio: "orion-02.mp3",
      who: "Narrator",
      text: "Bhima slays an elephant named Ashwatthama — a great beast of gold dust, no blood.",
    },
    {
      t: 36,
      plate: "dharma",
      zoom: 1.14,
      panX: 0.03,
      panY: -0.02,
      audio: "orion-03.mp3",
      who: "Narrator",
      text: "Yudhishthira must speak. Dharma tightens on the king who does not lie.",
    },
    {
      t: 48,
      plate: "conch",
      zoom: 1.16,
      panX: 0,
      panY: -0.03,
      audio: "orion-04.mp3",
      who: "Narrator",
      text: "Ashwatthama is dead, he says — and the elephant is lost under Krishna’s conch.",
    },
    {
      t: 60,
      plate: "yoga",
      zoom: 1.14,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-05.mp3",
      who: "Narrator",
      text: "Drona’s bow falls. He sits in yoga on the field.",
    },
    {
      t: 72,
      plate: "prince",
      zoom: 1.16,
      panX: -0.02,
      panY: -0.02,
      audio: "orion-06.mp3",
      who: "Narrator",
      text: "Dhrishtadyumna comes forth — the son born for this hour.",
    },
    {
      t: 84,
      plate: "still",
      zoom: 1.12,
      panX: 0.02,
      panY: 0.02,
      audio: "orion-07.mp3",
      who: "Narrator",
      text: "The guru is stilled as gold light — no blood, only a vow kept.",
    },
    {
      t: 95,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      audio: "orion-08.mp3",
      who: "Narrator",
      text: "Thus Drona falls. A son not on this field will hear it.",
    },
    {
      t: 102,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
