/**
 * Episode 14 — The Fall of Drona
 * Drona Parva · fifteenth day; the elephant; the half-truth; the guru sits
 * Logic pass 2026-09-29: unstoppable Drona → Krishna's stratagem → elephant Ashwatthama →
 * Drona asks Yudhishthira → half-truth ("the elephant" muttered) → chariot touches the earth →
 * Drona lays down arms, yoga → Dhrishtadyumna → beheading as gold light → Arjuna's grief/protest.
 * Sources: BORI CE/Debroy + Gita Press Gorakhpur + K.M. Ganguli (Drona Parva §190–196). See plate-bible source_block.
 */
export const EPISODE = {
  id: "14",
  slug: "drona-fall",
  title: "The Fall of Drona",
  subtitle: "Fifteenth day of Kurukshetra",
  style: "cinematic-plates",
  stillsDir: "episodes/14-drona-fall/stills/",
  voice: {
    provider: "local-kokoro",
    voice_id: "bm_george",
    cache: "ep14-local-20260929",
    note: "Kathavachak — Kokoro-82M bm_george (free local, Apache-2.0) via tools/render_local_voice.sh; Orion API retired 2026-09-29 (SuperGrok-only rule, no paid API). Files keep orion-NN.mp3 names/fingerprint.",
    base: "episodes/14-drona-fall/audio/",
  },
  music: {
    raga: "todi",
    note: "Miyan ki Todi — morning raga of pathos (komal Re/Ga/Dha, tivra Ma; Pa sparing). Tanpura + sparse bansuri, no tabla. Duck under narration.",
  },
  totalSec: 136,
  stills: {
    poster: "episodes/14-drona-fall/stills/poster.jpg",
  },
  plates: {
    wide: "plate-wide.jpg",
    counsel: "plate-counsel.jpg",
    elephant: "plate-elephant.jpg",
    dharma: "plate-dharma.jpg",
    conch: "plate-conch.jpg",
    wheel: "plate-wheel.jpg",
    yoga: "plate-yoga.jpg",
    prince: "plate-prince.jpg",
    still: "plate-still.jpg",
    grief: "plate-grief.jpg",
    "wide-gold": "plate-wide-gold.jpg",
  },
  end: {
    title: "End of Episode 14",
    line: "The guru is still. Elsewhere on the field, his son has heard.",
    next: "index.html",
    nextLabel: "All episodes",
  },
  palette: {
    cloth: "#c4a06a",
    vermillion: "#b83218",
    saffron: "#e08a1e",
    gold: "#e8c547",
    indigo: "#1a2744",
    leaf: "#2a5a38",
  },
  beats: [
    {
      t: 0,
      plate: "wide",
      zoom: 1.05,
      panX: 0,
      panY: 0,
      audio: "orion-00.mp3",
      who: "Narrator",
      text: "Dawn of the fifteenth day. Drona burns through the Pandava ranks — no one can stand before the guru.",
    },
    {
      t: 12,
      plate: "counsel",
      zoom: 1.14,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-01.mp3",
      who: "Narrator",
      text: "Krishna counsels: armed, he cannot be beaten — but he will lay down his bow if he believes his son Ashwatthama is dead.",
    },
    {
      t: 24,
      plate: "elephant",
      zoom: 1.12,
      panX: -0.02,
      panY: -0.02,
      audio: "orion-02.mp3",
      who: "Narrator",
      text: "So Bhima slays a great war-elephant named Ashwatthama — a beast, not the son.",
    },
    {
      t: 36,
      plate: "dharma",
      zoom: 1.14,
      panX: 0.03,
      panY: -0.02,
      audio: "orion-03.mp3",
      who: "Narrator",
      text: "Drona doubts Bhima’s cry. He asks Yudhishthira, who has never lied — and dharma tightens on the king.",
    },
    {
      t: 48,
      plate: "conch",
      zoom: 1.16,
      panX: 0,
      panY: -0.03,
      audio: "orion-04.mp3",
      who: "Narrator",
      text: "“Ashwatthama is dead,” he says aloud — and “the elephant” he mutters, lost under the roar of conches.",
    },
    {
      t: 60,
      plate: "wheel",
      zoom: 1.12,
      panX: 0.02,
      panY: 0.02,
      audio: "orion-05.mp3",
      who: "Narrator",
      text: "At that half-truth, his chariot — which had always ridden four fingers above the earth — sinks. Its wheels touch the ground.",
    },
    {
      t: 72,
      plate: "yoga",
      zoom: 1.14,
      panX: 0.02,
      panY: -0.02,
      audio: "orion-06.mp3",
      who: "Narrator",
      text: "Drona lays down his weapons. He sits in yoga, and turns his mind inward.",
    },
    {
      t: 84,
      plate: "prince",
      zoom: 1.16,
      panX: -0.02,
      panY: -0.02,
      audio: "orion-07.mp3",
      who: "Narrator",
      text: "Dhrishtadyumna — born from Drupada’s fire to end Drona — comes forth with his sword.",
    },
    {
      t: 96,
      plate: "still",
      zoom: 1.12,
      panX: 0.02,
      panY: 0.02,
      audio: "orion-08.mp3",
      who: "Narrator",
      text: "He strikes off the guru’s head — but Drona’s spirit had already risen as light, seen by only a few.",
    },
    {
      t: 108,
      plate: "grief",
      zoom: 1.12,
      panX: -0.02,
      panY: -0.02,
      audio: "orion-09.mp3",
      who: "Narrator",
      text: "Arjuna had cried, “Bring him alive!” Now he weeps — and rebukes the lie that disarmed his teacher.",
    },
    {
      t: 120,
      plate: "wide-gold",
      zoom: 1.08,
      panX: 0,
      panY: 0.02,
      audio: "orion-10.mp3",
      who: "Narrator",
      text: "Thus Drona falls. Elsewhere on the field, his son hears it — and Ashwatthama’s wrath is coming.",
    },
    {
      t: 132,
      plate: "wide-gold",
      zoom: 1.02,
      panX: 0,
      panY: 0,
      who: "",
      text: "",
    },
  ],
};
